// Code generated by protoc-gen-go. DO NOT EDIT.
// source: viewer.proto

package viewerdbpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ViewerType - Viewer type
//            - 数据类型
type ViewerType int32

const (
	ViewerType_EMPTY    ViewerType = 0
	ViewerType_GRAPH    ViewerType = 1
	ViewerType_JSON     ViewerType = 2
	ViewerType_LINE     ViewerType = 3
	ViewerType_MULTI    ViewerType = 4
	ViewerType_PIE      ViewerType = 5
	ViewerType_SCATTER  ViewerType = 6
	ViewerType_BOXPLOT  ViewerType = 7
	ViewerType_DTGAME6  ViewerType = 8
	ViewerType_SCATTER2 ViewerType = 9
	ViewerType_BOXPLOT2 ViewerType = 10
	ViewerType_BOXPLOT3 ViewerType = 11
)

var ViewerType_name = map[int32]string{
	0:  "EMPTY",
	1:  "GRAPH",
	2:  "JSON",
	3:  "LINE",
	4:  "MULTI",
	5:  "PIE",
	6:  "SCATTER",
	7:  "BOXPLOT",
	8:  "DTGAME6",
	9:  "SCATTER2",
	10: "BOXPLOT2",
	11: "BOXPLOT3",
}
var ViewerType_value = map[string]int32{
	"EMPTY":    0,
	"GRAPH":    1,
	"JSON":     2,
	"LINE":     3,
	"MULTI":    4,
	"PIE":      5,
	"SCATTER":  6,
	"BOXPLOT":  7,
	"DTGAME6":  8,
	"SCATTER2": 9,
	"BOXPLOT2": 10,
	"BOXPLOT3": 11,
}

func (x ViewerType) String() string {
	return proto.EnumName(ViewerType_name, int32(x))
}
func (ViewerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{0}
}

// ValueType - Value type
//           - 数据类型
type ValueType int32

const (
	ValueType_NULLTYPE ValueType = 0
	ValueType_INT32    ValueType = 1
	ValueType_INT64    ValueType = 2
	ValueType_FLOAT32  ValueType = 3
	ValueType_FLOAT64  ValueType = 4
	ValueType_STRING   ValueType = 5
)

var ValueType_name = map[int32]string{
	0: "NULLTYPE",
	1: "INT32",
	2: "INT64",
	3: "FLOAT32",
	4: "FLOAT64",
	5: "STRING",
}
var ValueType_value = map[string]int32{
	"NULLTYPE": 0,
	"INT32":    1,
	"INT64":    2,
	"FLOAT32":  3,
	"FLOAT64":  4,
	"STRING":   5,
}

func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{1}
}

// DTGame6ArrayType - Array Type
//                  - 数据类型
type DTGame6ArrayType int32

const (
	// 行优先
	DTGame6ArrayType_ROW DTGame6ArrayType = 0
	// 列优先
	DTGame6ArrayType_COLUMN DTGame6ArrayType = 1
)

var DTGame6ArrayType_name = map[int32]string{
	0: "ROW",
	1: "COLUMN",
}
var DTGame6ArrayType_value = map[string]int32{
	"ROW":    0,
	"COLUMN": 1,
}

func (x DTGame6ArrayType) String() string {
	return proto.EnumName(DTGame6ArrayType_name, int32(x))
}
func (DTGame6ArrayType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{2}
}

// GraphNode - Graph node
//           - 图节点
type GraphNode struct {
	// id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// size
	Size int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// category
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphNode) Reset()         { *m = GraphNode{} }
func (m *GraphNode) String() string { return proto.CompactTextString(m) }
func (*GraphNode) ProtoMessage()    {}
func (*GraphNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{0}
}
func (m *GraphNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphNode.Unmarshal(m, b)
}
func (m *GraphNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphNode.Marshal(b, m, deterministic)
}
func (dst *GraphNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphNode.Merge(dst, src)
}
func (m *GraphNode) XXX_Size() int {
	return xxx_messageInfo_GraphNode.Size(m)
}
func (m *GraphNode) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphNode.DiscardUnknown(m)
}

var xxx_messageInfo_GraphNode proto.InternalMessageInfo

func (m *GraphNode) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GraphNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphNode) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GraphNode) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

// GraphLink - Graph link info
//           - 图节点连接关系
type GraphLink struct {
	// src
	Src int32 `protobuf:"varint,1,opt,name=src,proto3" json:"src,omitempty"`
	// dest
	Dest int32 `protobuf:"varint,2,opt,name=dest,proto3" json:"dest,omitempty"`
	// size
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphLink) Reset()         { *m = GraphLink{} }
func (m *GraphLink) String() string { return proto.CompactTextString(m) }
func (*GraphLink) ProtoMessage()    {}
func (*GraphLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{1}
}
func (m *GraphLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphLink.Unmarshal(m, b)
}
func (m *GraphLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphLink.Marshal(b, m, deterministic)
}
func (dst *GraphLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphLink.Merge(dst, src)
}
func (m *GraphLink) XXX_Size() int {
	return xxx_messageInfo_GraphLink.Size(m)
}
func (m *GraphLink) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphLink.DiscardUnknown(m)
}

var xxx_messageInfo_GraphLink proto.InternalMessageInfo

func (m *GraphLink) GetSrc() int32 {
	if m != nil {
		return m.Src
	}
	return 0
}

func (m *GraphLink) GetDest() int32 {
	if m != nil {
		return m.Dest
	}
	return 0
}

func (m *GraphLink) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

// GraphData - Graph data
//           - 图节点完整数据
type GraphData struct {
	// nodes
	Nodes []*GraphNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// links
	Links                []*GraphLink `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GraphData) Reset()         { *m = GraphData{} }
func (m *GraphData) String() string { return proto.CompactTextString(m) }
func (*GraphData) ProtoMessage()    {}
func (*GraphData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{2}
}
func (m *GraphData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphData.Unmarshal(m, b)
}
func (m *GraphData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphData.Marshal(b, m, deterministic)
}
func (dst *GraphData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphData.Merge(dst, src)
}
func (m *GraphData) XXX_Size() int {
	return xxx_messageInfo_GraphData.Size(m)
}
func (m *GraphData) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphData.DiscardUnknown(m)
}

var xxx_messageInfo_GraphData proto.InternalMessageInfo

func (m *GraphData) GetNodes() []*GraphNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *GraphData) GetLinks() []*GraphLink {
	if m != nil {
		return m.Links
	}
	return nil
}

// JSONData - JSON data
//          - json格式的数据
type JSONData struct {
	// string for json
	Str                  string   `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JSONData) Reset()         { *m = JSONData{} }
func (m *JSONData) String() string { return proto.CompactTextString(m) }
func (*JSONData) ProtoMessage()    {}
func (*JSONData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{3}
}
func (m *JSONData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSONData.Unmarshal(m, b)
}
func (m *JSONData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSONData.Marshal(b, m, deterministic)
}
func (dst *JSONData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSONData.Merge(dst, src)
}
func (m *JSONData) XXX_Size() int {
	return xxx_messageInfo_JSONData.Size(m)
}
func (m *JSONData) XXX_DiscardUnknown() {
	xxx_messageInfo_JSONData.DiscardUnknown(m)
}

var xxx_messageInfo_JSONData proto.InternalMessageInfo

func (m *JSONData) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

// LineSeriesData - Line series data
//                - 折线图数据
type LineSeriesData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ValString            []string `protobuf:"bytes,2,rep,name=valString,proto3" json:"valString,omitempty"`
	ValInt32             []int32  `protobuf:"varint,3,rep,packed,name=valInt32,proto3" json:"valInt32,omitempty"`
	ValInt64             []int64  `protobuf:"varint,4,rep,packed,name=valInt64,proto3" json:"valInt64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LineSeriesData) Reset()         { *m = LineSeriesData{} }
func (m *LineSeriesData) String() string { return proto.CompactTextString(m) }
func (*LineSeriesData) ProtoMessage()    {}
func (*LineSeriesData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{4}
}
func (m *LineSeriesData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineSeriesData.Unmarshal(m, b)
}
func (m *LineSeriesData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineSeriesData.Marshal(b, m, deterministic)
}
func (dst *LineSeriesData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineSeriesData.Merge(dst, src)
}
func (m *LineSeriesData) XXX_Size() int {
	return xxx_messageInfo_LineSeriesData.Size(m)
}
func (m *LineSeriesData) XXX_DiscardUnknown() {
	xxx_messageInfo_LineSeriesData.DiscardUnknown(m)
}

var xxx_messageInfo_LineSeriesData proto.InternalMessageInfo

func (m *LineSeriesData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LineSeriesData) GetValString() []string {
	if m != nil {
		return m.ValString
	}
	return nil
}

func (m *LineSeriesData) GetValInt32() []int32 {
	if m != nil {
		return m.ValInt32
	}
	return nil
}

func (m *LineSeriesData) GetValInt64() []int64 {
	if m != nil {
		return m.ValInt64
	}
	return nil
}

// LineData - Line data
//           - 折线图完整数据
type LineData struct {
	// xAxisType
	XAxisType string `protobuf:"bytes,1,opt,name=xAxisType,proto3" json:"xAxisType,omitempty"`
	// xAxisString
	XAxisString []string `protobuf:"bytes,2,rep,name=xAxisString,proto3" json:"xAxisString,omitempty"`
	// xAxisInt32
	XAxisInt32 []int32 `protobuf:"varint,3,rep,packed,name=xAxisInt32,proto3" json:"xAxisInt32,omitempty"`
	// xAxisInt64
	XAxisInt64 []int64 `protobuf:"varint,4,rep,packed,name=xAxisInt64,proto3" json:"xAxisInt64,omitempty"`
	// yAxisType
	YAxisType string `protobuf:"bytes,100,opt,name=yAxisType,proto3" json:"yAxisType,omitempty"`
	// xAxisData
	Series               []*LineSeriesData `protobuf:"bytes,101,rep,name=series,proto3" json:"series,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LineData) Reset()         { *m = LineData{} }
func (m *LineData) String() string { return proto.CompactTextString(m) }
func (*LineData) ProtoMessage()    {}
func (*LineData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{5}
}
func (m *LineData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineData.Unmarshal(m, b)
}
func (m *LineData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineData.Marshal(b, m, deterministic)
}
func (dst *LineData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineData.Merge(dst, src)
}
func (m *LineData) XXX_Size() int {
	return xxx_messageInfo_LineData.Size(m)
}
func (m *LineData) XXX_DiscardUnknown() {
	xxx_messageInfo_LineData.DiscardUnknown(m)
}

var xxx_messageInfo_LineData proto.InternalMessageInfo

func (m *LineData) GetXAxisType() string {
	if m != nil {
		return m.XAxisType
	}
	return ""
}

func (m *LineData) GetXAxisString() []string {
	if m != nil {
		return m.XAxisString
	}
	return nil
}

func (m *LineData) GetXAxisInt32() []int32 {
	if m != nil {
		return m.XAxisInt32
	}
	return nil
}

func (m *LineData) GetXAxisInt64() []int64 {
	if m != nil {
		return m.XAxisInt64
	}
	return nil
}

func (m *LineData) GetYAxisType() string {
	if m != nil {
		return m.YAxisType
	}
	return ""
}

func (m *LineData) GetSeries() []*LineSeriesData {
	if m != nil {
		return m.Series
	}
	return nil
}

// MultiData - Multi data
//           - 多数据模式完整数据
type MultiData struct {
	// tokens
	Tokens               []string `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiData) Reset()         { *m = MultiData{} }
func (m *MultiData) String() string { return proto.CompactTextString(m) }
func (*MultiData) ProtoMessage()    {}
func (*MultiData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{6}
}
func (m *MultiData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiData.Unmarshal(m, b)
}
func (m *MultiData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiData.Marshal(b, m, deterministic)
}
func (dst *MultiData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiData.Merge(dst, src)
}
func (m *MultiData) XXX_Size() int {
	return xxx_messageInfo_MultiData.Size(m)
}
func (m *MultiData) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiData.DiscardUnknown(m)
}

var xxx_messageInfo_MultiData proto.InternalMessageInfo

func (m *MultiData) GetTokens() []string {
	if m != nil {
		return m.Tokens
	}
	return nil
}

// PieDataInfo - Pie data info
//             - 饼图完整数据
type PieDataInfo struct {
	// name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// valInt32
	ValInt32 int32 `protobuf:"varint,2,opt,name=valInt32,proto3" json:"valInt32,omitempty"`
	// valInt64
	ValInt64             int64    `protobuf:"varint,3,opt,name=valInt64,proto3" json:"valInt64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieDataInfo) Reset()         { *m = PieDataInfo{} }
func (m *PieDataInfo) String() string { return proto.CompactTextString(m) }
func (*PieDataInfo) ProtoMessage()    {}
func (*PieDataInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{7}
}
func (m *PieDataInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieDataInfo.Unmarshal(m, b)
}
func (m *PieDataInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieDataInfo.Marshal(b, m, deterministic)
}
func (dst *PieDataInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieDataInfo.Merge(dst, src)
}
func (m *PieDataInfo) XXX_Size() int {
	return xxx_messageInfo_PieDataInfo.Size(m)
}
func (m *PieDataInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PieDataInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PieDataInfo proto.InternalMessageInfo

func (m *PieDataInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PieDataInfo) GetValInt32() int32 {
	if m != nil {
		return m.ValInt32
	}
	return 0
}

func (m *PieDataInfo) GetValInt64() int64 {
	if m != nil {
		return m.ValInt64
	}
	return 0
}

// PieData - Pie data
//         - 饼图完整数据
type PieData struct {
	// name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// tokens
	Data                 []*PieDataInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PieData) Reset()         { *m = PieData{} }
func (m *PieData) String() string { return proto.CompactTextString(m) }
func (*PieData) ProtoMessage()    {}
func (*PieData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{8}
}
func (m *PieData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieData.Unmarshal(m, b)
}
func (m *PieData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieData.Marshal(b, m, deterministic)
}
func (dst *PieData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieData.Merge(dst, src)
}
func (m *PieData) XXX_Size() int {
	return xxx_messageInfo_PieData.Size(m)
}
func (m *PieData) XXX_DiscardUnknown() {
	xxx_messageInfo_PieData.DiscardUnknown(m)
}

var xxx_messageInfo_PieData proto.InternalMessageInfo

func (m *PieData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PieData) GetData() []*PieDataInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

// ScatterNode - scatter node
//             - 散点图数据
type ScatterNode struct {
	// xInt32
	XInt32 int32 `protobuf:"varint,1,opt,name=xInt32,proto3" json:"xInt32,omitempty"`
	// xInt64
	XInt64 int64 `protobuf:"varint,2,opt,name=xInt64,proto3" json:"xInt64,omitempty"`
	// yInt32
	YInt32 int32 `protobuf:"varint,100,opt,name=yInt32,proto3" json:"yInt32,omitempty"`
	// xInt64
	YInt64               int64    `protobuf:"varint,101,opt,name=yInt64,proto3" json:"yInt64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScatterNode) Reset()         { *m = ScatterNode{} }
func (m *ScatterNode) String() string { return proto.CompactTextString(m) }
func (*ScatterNode) ProtoMessage()    {}
func (*ScatterNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{9}
}
func (m *ScatterNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScatterNode.Unmarshal(m, b)
}
func (m *ScatterNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScatterNode.Marshal(b, m, deterministic)
}
func (dst *ScatterNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScatterNode.Merge(dst, src)
}
func (m *ScatterNode) XXX_Size() int {
	return xxx_messageInfo_ScatterNode.Size(m)
}
func (m *ScatterNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ScatterNode.DiscardUnknown(m)
}

var xxx_messageInfo_ScatterNode proto.InternalMessageInfo

func (m *ScatterNode) GetXInt32() int32 {
	if m != nil {
		return m.XInt32
	}
	return 0
}

func (m *ScatterNode) GetXInt64() int64 {
	if m != nil {
		return m.XInt64
	}
	return 0
}

func (m *ScatterNode) GetYInt32() int32 {
	if m != nil {
		return m.YInt32
	}
	return 0
}

func (m *ScatterNode) GetYInt64() int64 {
	if m != nil {
		return m.YInt64
	}
	return 0
}

// ScatterData - scatter data
//             - 散点图数据
type ScatterData struct {
	XType                ValueType      `protobuf:"varint,1,opt,name=xType,proto3,enum=viewerdbpb.ValueType" json:"xType,omitempty"`
	YType                ValueType      `protobuf:"varint,2,opt,name=yType,proto3,enum=viewerdbpb.ValueType" json:"yType,omitempty"`
	Data                 []*ScatterNode `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Name                 string         `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ScatterData) Reset()         { *m = ScatterData{} }
func (m *ScatterData) String() string { return proto.CompactTextString(m) }
func (*ScatterData) ProtoMessage()    {}
func (*ScatterData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{10}
}
func (m *ScatterData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScatterData.Unmarshal(m, b)
}
func (m *ScatterData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScatterData.Marshal(b, m, deterministic)
}
func (dst *ScatterData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScatterData.Merge(dst, src)
}
func (m *ScatterData) XXX_Size() int {
	return xxx_messageInfo_ScatterData.Size(m)
}
func (m *ScatterData) XXX_DiscardUnknown() {
	xxx_messageInfo_ScatterData.DiscardUnknown(m)
}

var xxx_messageInfo_ScatterData proto.InternalMessageInfo

func (m *ScatterData) GetXType() ValueType {
	if m != nil {
		return m.XType
	}
	return ValueType_NULLTYPE
}

func (m *ScatterData) GetYType() ValueType {
	if m != nil {
		return m.YType
	}
	return ValueType_NULLTYPE
}

func (m *ScatterData) GetData() []*ScatterNode {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ScatterData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Scatter2Data - scatter2 data
//             - 散点图数据
type Scatter2Data struct {
	Lst                  []*ScatterData `protobuf:"bytes,1,rep,name=lst,proto3" json:"lst,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Scatter2Data) Reset()         { *m = Scatter2Data{} }
func (m *Scatter2Data) String() string { return proto.CompactTextString(m) }
func (*Scatter2Data) ProtoMessage()    {}
func (*Scatter2Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{11}
}
func (m *Scatter2Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scatter2Data.Unmarshal(m, b)
}
func (m *Scatter2Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scatter2Data.Marshal(b, m, deterministic)
}
func (dst *Scatter2Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scatter2Data.Merge(dst, src)
}
func (m *Scatter2Data) XXX_Size() int {
	return xxx_messageInfo_Scatter2Data.Size(m)
}
func (m *Scatter2Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Scatter2Data.DiscardUnknown(m)
}

var xxx_messageInfo_Scatter2Data proto.InternalMessageInfo

func (m *Scatter2Data) GetLst() []*ScatterData {
	if m != nil {
		return m.Lst
	}
	return nil
}

// Dataset - dataset
//             - dataset
type Dataset struct {
	Name                 string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ValType              ValueType `protobuf:"varint,2,opt,name=valType,proto3,enum=viewerdbpb.ValueType" json:"valType,omitempty"`
	ArrInt32             []int32   `protobuf:"varint,3,rep,packed,name=arrInt32,proto3" json:"arrInt32,omitempty"`
	ArrInt64             []int64   `protobuf:"varint,4,rep,packed,name=arrInt64,proto3" json:"arrInt64,omitempty"`
	ArrFloat32           []float32 `protobuf:"fixed32,5,rep,packed,name=arrFloat32,proto3" json:"arrFloat32,omitempty"`
	ArrFloat64           []float64 `protobuf:"fixed64,6,rep,packed,name=arrFloat64,proto3" json:"arrFloat64,omitempty"`
	ArrString            []string  `protobuf:"bytes,7,rep,name=arrString,proto3" json:"arrString,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Dataset) Reset()         { *m = Dataset{} }
func (m *Dataset) String() string { return proto.CompactTextString(m) }
func (*Dataset) ProtoMessage()    {}
func (*Dataset) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{12}
}
func (m *Dataset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dataset.Unmarshal(m, b)
}
func (m *Dataset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dataset.Marshal(b, m, deterministic)
}
func (dst *Dataset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dataset.Merge(dst, src)
}
func (m *Dataset) XXX_Size() int {
	return xxx_messageInfo_Dataset.Size(m)
}
func (m *Dataset) XXX_DiscardUnknown() {
	xxx_messageInfo_Dataset.DiscardUnknown(m)
}

var xxx_messageInfo_Dataset proto.InternalMessageInfo

func (m *Dataset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Dataset) GetValType() ValueType {
	if m != nil {
		return m.ValType
	}
	return ValueType_NULLTYPE
}

func (m *Dataset) GetArrInt32() []int32 {
	if m != nil {
		return m.ArrInt32
	}
	return nil
}

func (m *Dataset) GetArrInt64() []int64 {
	if m != nil {
		return m.ArrInt64
	}
	return nil
}

func (m *Dataset) GetArrFloat32() []float32 {
	if m != nil {
		return m.ArrFloat32
	}
	return nil
}

func (m *Dataset) GetArrFloat64() []float64 {
	if m != nil {
		return m.ArrFloat64
	}
	return nil
}

func (m *Dataset) GetArrString() []string {
	if m != nil {
		return m.ArrString
	}
	return nil
}

// BoxplotNode - boxplot node
//             - 盒须图数据
type BoxplotNode struct {
	Name                 string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ValType              ValueType `protobuf:"varint,2,opt,name=valType,proto3,enum=viewerdbpb.ValueType" json:"valType,omitempty"`
	ArrInt32             []int32   `protobuf:"varint,3,rep,packed,name=arrInt32,proto3" json:"arrInt32,omitempty"`
	ArrInt64             []int64   `protobuf:"varint,4,rep,packed,name=arrInt64,proto3" json:"arrInt64,omitempty"`
	ArrFloat32           []float32 `protobuf:"fixed32,5,rep,packed,name=arrFloat32,proto3" json:"arrFloat32,omitempty"`
	ArrFloat64           []float64 `protobuf:"fixed64,6,rep,packed,name=arrFloat64,proto3" json:"arrFloat64,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BoxplotNode) Reset()         { *m = BoxplotNode{} }
func (m *BoxplotNode) String() string { return proto.CompactTextString(m) }
func (*BoxplotNode) ProtoMessage()    {}
func (*BoxplotNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{13}
}
func (m *BoxplotNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxplotNode.Unmarshal(m, b)
}
func (m *BoxplotNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxplotNode.Marshal(b, m, deterministic)
}
func (dst *BoxplotNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxplotNode.Merge(dst, src)
}
func (m *BoxplotNode) XXX_Size() int {
	return xxx_messageInfo_BoxplotNode.Size(m)
}
func (m *BoxplotNode) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxplotNode.DiscardUnknown(m)
}

var xxx_messageInfo_BoxplotNode proto.InternalMessageInfo

func (m *BoxplotNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BoxplotNode) GetValType() ValueType {
	if m != nil {
		return m.ValType
	}
	return ValueType_NULLTYPE
}

func (m *BoxplotNode) GetArrInt32() []int32 {
	if m != nil {
		return m.ArrInt32
	}
	return nil
}

func (m *BoxplotNode) GetArrInt64() []int64 {
	if m != nil {
		return m.ArrInt64
	}
	return nil
}

func (m *BoxplotNode) GetArrFloat32() []float32 {
	if m != nil {
		return m.ArrFloat32
	}
	return nil
}

func (m *BoxplotNode) GetArrFloat64() []float64 {
	if m != nil {
		return m.ArrFloat64
	}
	return nil
}

// BoxplotData - boxplot data
//             - 盒须图数据
type BoxplotData struct {
	Data                 []*BoxplotNode `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Category             string         `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BoxplotData) Reset()         { *m = BoxplotData{} }
func (m *BoxplotData) String() string { return proto.CompactTextString(m) }
func (*BoxplotData) ProtoMessage()    {}
func (*BoxplotData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{14}
}
func (m *BoxplotData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxplotData.Unmarshal(m, b)
}
func (m *BoxplotData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxplotData.Marshal(b, m, deterministic)
}
func (dst *BoxplotData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxplotData.Merge(dst, src)
}
func (m *BoxplotData) XXX_Size() int {
	return xxx_messageInfo_BoxplotData.Size(m)
}
func (m *BoxplotData) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxplotData.DiscardUnknown(m)
}

var xxx_messageInfo_BoxplotData proto.InternalMessageInfo

func (m *BoxplotData) GetData() []*BoxplotNode {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BoxplotData) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

// Boxplot2Data - boxplot2 data
//             - 盒须图数据
type Boxplot2Data struct {
	Lst                  []*BoxplotData `protobuf:"bytes,1,rep,name=lst,proto3" json:"lst,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Boxplot2Data) Reset()         { *m = Boxplot2Data{} }
func (m *Boxplot2Data) String() string { return proto.CompactTextString(m) }
func (*Boxplot2Data) ProtoMessage()    {}
func (*Boxplot2Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{15}
}
func (m *Boxplot2Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boxplot2Data.Unmarshal(m, b)
}
func (m *Boxplot2Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boxplot2Data.Marshal(b, m, deterministic)
}
func (dst *Boxplot2Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boxplot2Data.Merge(dst, src)
}
func (m *Boxplot2Data) XXX_Size() int {
	return xxx_messageInfo_Boxplot2Data.Size(m)
}
func (m *Boxplot2Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Boxplot2Data.DiscardUnknown(m)
}

var xxx_messageInfo_Boxplot2Data proto.InternalMessageInfo

func (m *Boxplot2Data) GetLst() []*BoxplotData {
	if m != nil {
		return m.Lst
	}
	return nil
}

// Boxplot3 - boxplot3
//          - 盒须图数据
type Boxplot3 struct {
	Category             string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	DatasetName          []string `protobuf:"bytes,2,rep,name=datasetName,proto3" json:"datasetName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Boxplot3) Reset()         { *m = Boxplot3{} }
func (m *Boxplot3) String() string { return proto.CompactTextString(m) }
func (*Boxplot3) ProtoMessage()    {}
func (*Boxplot3) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{16}
}
func (m *Boxplot3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boxplot3.Unmarshal(m, b)
}
func (m *Boxplot3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boxplot3.Marshal(b, m, deterministic)
}
func (dst *Boxplot3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boxplot3.Merge(dst, src)
}
func (m *Boxplot3) XXX_Size() int {
	return xxx_messageInfo_Boxplot3.Size(m)
}
func (m *Boxplot3) XXX_DiscardUnknown() {
	xxx_messageInfo_Boxplot3.DiscardUnknown(m)
}

var xxx_messageInfo_Boxplot3 proto.InternalMessageInfo

func (m *Boxplot3) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Boxplot3) GetDatasetName() []string {
	if m != nil {
		return m.DatasetName
	}
	return nil
}

// Boxplot3Data - boxplot3 data
//              - 盒须图数据
type Boxplot3Data struct {
	Datasets             map[string]*Dataset `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Boxplots             []*Boxplot3         `protobuf:"bytes,2,rep,name=boxplots,proto3" json:"boxplots,omitempty"`
	XVal                 *Dataset            `protobuf:"bytes,3,opt,name=xVal,proto3" json:"xVal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Boxplot3Data) Reset()         { *m = Boxplot3Data{} }
func (m *Boxplot3Data) String() string { return proto.CompactTextString(m) }
func (*Boxplot3Data) ProtoMessage()    {}
func (*Boxplot3Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{17}
}
func (m *Boxplot3Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boxplot3Data.Unmarshal(m, b)
}
func (m *Boxplot3Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boxplot3Data.Marshal(b, m, deterministic)
}
func (dst *Boxplot3Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boxplot3Data.Merge(dst, src)
}
func (m *Boxplot3Data) XXX_Size() int {
	return xxx_messageInfo_Boxplot3Data.Size(m)
}
func (m *Boxplot3Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Boxplot3Data.DiscardUnknown(m)
}

var xxx_messageInfo_Boxplot3Data proto.InternalMessageInfo

func (m *Boxplot3Data) GetDatasets() map[string]*Dataset {
	if m != nil {
		return m.Datasets
	}
	return nil
}

func (m *Boxplot3Data) GetBoxplots() []*Boxplot3 {
	if m != nil {
		return m.Boxplots
	}
	return nil
}

func (m *Boxplot3Data) GetXVal() *Dataset {
	if m != nil {
		return m.XVal
	}
	return nil
}

// DTGame6List - dtgame6 list
//             - dtgame6
type DTGame6List struct {
	Arr                  []int32  `protobuf:"varint,1,rep,packed,name=arr,proto3" json:"arr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DTGame6List) Reset()         { *m = DTGame6List{} }
func (m *DTGame6List) String() string { return proto.CompactTextString(m) }
func (*DTGame6List) ProtoMessage()    {}
func (*DTGame6List) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{18}
}
func (m *DTGame6List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DTGame6List.Unmarshal(m, b)
}
func (m *DTGame6List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DTGame6List.Marshal(b, m, deterministic)
}
func (dst *DTGame6List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DTGame6List.Merge(dst, src)
}
func (m *DTGame6List) XXX_Size() int {
	return xxx_messageInfo_DTGame6List.Size(m)
}
func (m *DTGame6List) XXX_DiscardUnknown() {
	xxx_messageInfo_DTGame6List.DiscardUnknown(m)
}

var xxx_messageInfo_DTGame6List proto.InternalMessageInfo

func (m *DTGame6List) GetArr() []int32 {
	if m != nil {
		return m.Arr
	}
	return nil
}

// DTGame6Pos - dtgame6 pos
//            - dtgame6
type DTGame6Pos struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DTGame6Pos) Reset()         { *m = DTGame6Pos{} }
func (m *DTGame6Pos) String() string { return proto.CompactTextString(m) }
func (*DTGame6Pos) ProtoMessage()    {}
func (*DTGame6Pos) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{19}
}
func (m *DTGame6Pos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DTGame6Pos.Unmarshal(m, b)
}
func (m *DTGame6Pos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DTGame6Pos.Marshal(b, m, deterministic)
}
func (dst *DTGame6Pos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DTGame6Pos.Merge(dst, src)
}
func (m *DTGame6Pos) XXX_Size() int {
	return xxx_messageInfo_DTGame6Pos.Size(m)
}
func (m *DTGame6Pos) XXX_DiscardUnknown() {
	xxx_messageInfo_DTGame6Pos.DiscardUnknown(m)
}

var xxx_messageInfo_DTGame6Pos proto.InternalMessageInfo

func (m *DTGame6Pos) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *DTGame6Pos) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

// DTGame6Result - dtgame6 game result
//               - dtgame6
type DTGame6Result struct {
	Type                 string        `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Bet                  int32         `protobuf:"varint,2,opt,name=bet,proto3" json:"bet,omitempty"`
	RealBet              int32         `protobuf:"varint,3,opt,name=realBet,proto3" json:"realBet,omitempty"`
	BaseMul              int32         `protobuf:"varint,4,opt,name=baseMul,proto3" json:"baseMul,omitempty"`
	Win                  int32         `protobuf:"varint,5,opt,name=win,proto3" json:"win,omitempty"`
	RealWin              int32         `protobuf:"varint,6,opt,name=realWin,proto3" json:"realWin,omitempty"`
	BonusPrize           int32         `protobuf:"varint,7,opt,name=bonusPrize,proto3" json:"bonusPrize,omitempty"`
	OtherMul             int32         `protobuf:"varint,8,opt,name=otherMul,proto3" json:"otherMul,omitempty"`
	Pos                  []*DTGame6Pos `protobuf:"bytes,100,rep,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DTGame6Result) Reset()         { *m = DTGame6Result{} }
func (m *DTGame6Result) String() string { return proto.CompactTextString(m) }
func (*DTGame6Result) ProtoMessage()    {}
func (*DTGame6Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{20}
}
func (m *DTGame6Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DTGame6Result.Unmarshal(m, b)
}
func (m *DTGame6Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DTGame6Result.Marshal(b, m, deterministic)
}
func (dst *DTGame6Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DTGame6Result.Merge(dst, src)
}
func (m *DTGame6Result) XXX_Size() int {
	return xxx_messageInfo_DTGame6Result.Size(m)
}
func (m *DTGame6Result) XXX_DiscardUnknown() {
	xxx_messageInfo_DTGame6Result.DiscardUnknown(m)
}

var xxx_messageInfo_DTGame6Result proto.InternalMessageInfo

func (m *DTGame6Result) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DTGame6Result) GetBet() int32 {
	if m != nil {
		return m.Bet
	}
	return 0
}

func (m *DTGame6Result) GetRealBet() int32 {
	if m != nil {
		return m.RealBet
	}
	return 0
}

func (m *DTGame6Result) GetBaseMul() int32 {
	if m != nil {
		return m.BaseMul
	}
	return 0
}

func (m *DTGame6Result) GetWin() int32 {
	if m != nil {
		return m.Win
	}
	return 0
}

func (m *DTGame6Result) GetRealWin() int32 {
	if m != nil {
		return m.RealWin
	}
	return 0
}

func (m *DTGame6Result) GetBonusPrize() int32 {
	if m != nil {
		return m.BonusPrize
	}
	return 0
}

func (m *DTGame6Result) GetOtherMul() int32 {
	if m != nil {
		return m.OtherMul
	}
	return 0
}

func (m *DTGame6Result) GetPos() []*DTGame6Pos {
	if m != nil {
		return m.Pos
	}
	return nil
}

// DTGame6Data - dtgame6 data
//             - dtgame6
type DTGame6Data struct {
	GameCode             string           `protobuf:"bytes,1,opt,name=gameCode,proto3" json:"gameCode,omitempty"`
	GameModule           string           `protobuf:"bytes,2,opt,name=gameModule,proto3" json:"gameModule,omitempty"`
	ListParent           []string         `protobuf:"bytes,3,rep,name=listParent,proto3" json:"listParent,omitempty"`
	ArrType              DTGame6ArrayType `protobuf:"varint,100,opt,name=arrType,proto3,enum=viewerdbpb.DTGame6ArrayType" json:"arrType,omitempty"`
	Arr                  []*DTGame6List   `protobuf:"bytes,101,rep,name=arr,proto3" json:"arr,omitempty"`
	Bet                  int32            `protobuf:"varint,200,opt,name=bet,proto3" json:"bet,omitempty"`
	RealBet              int32            `protobuf:"varint,201,opt,name=realBet,proto3" json:"realBet,omitempty"`
	Win                  int32            `protobuf:"varint,202,opt,name=win,proto3" json:"win,omitempty"`
	RealWin              int32            `protobuf:"varint,203,opt,name=realWin,proto3" json:"realWin,omitempty"`
	Results              []*DTGame6Result `protobuf:"bytes,204,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DTGame6Data) Reset()         { *m = DTGame6Data{} }
func (m *DTGame6Data) String() string { return proto.CompactTextString(m) }
func (*DTGame6Data) ProtoMessage()    {}
func (*DTGame6Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{21}
}
func (m *DTGame6Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DTGame6Data.Unmarshal(m, b)
}
func (m *DTGame6Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DTGame6Data.Marshal(b, m, deterministic)
}
func (dst *DTGame6Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DTGame6Data.Merge(dst, src)
}
func (m *DTGame6Data) XXX_Size() int {
	return xxx_messageInfo_DTGame6Data.Size(m)
}
func (m *DTGame6Data) XXX_DiscardUnknown() {
	xxx_messageInfo_DTGame6Data.DiscardUnknown(m)
}

var xxx_messageInfo_DTGame6Data proto.InternalMessageInfo

func (m *DTGame6Data) GetGameCode() string {
	if m != nil {
		return m.GameCode
	}
	return ""
}

func (m *DTGame6Data) GetGameModule() string {
	if m != nil {
		return m.GameModule
	}
	return ""
}

func (m *DTGame6Data) GetListParent() []string {
	if m != nil {
		return m.ListParent
	}
	return nil
}

func (m *DTGame6Data) GetArrType() DTGame6ArrayType {
	if m != nil {
		return m.ArrType
	}
	return DTGame6ArrayType_ROW
}

func (m *DTGame6Data) GetArr() []*DTGame6List {
	if m != nil {
		return m.Arr
	}
	return nil
}

func (m *DTGame6Data) GetBet() int32 {
	if m != nil {
		return m.Bet
	}
	return 0
}

func (m *DTGame6Data) GetRealBet() int32 {
	if m != nil {
		return m.RealBet
	}
	return 0
}

func (m *DTGame6Data) GetWin() int32 {
	if m != nil {
		return m.Win
	}
	return 0
}

func (m *DTGame6Data) GetRealWin() int32 {
	if m != nil {
		return m.RealWin
	}
	return 0
}

func (m *DTGame6Data) GetResults() []*DTGame6Result {
	if m != nil {
		return m.Results
	}
	return nil
}

// ViewerData - viewer data
//            - viewer数据
type ViewerData struct {
	// type
	Type ViewerType `protobuf:"varint,1,opt,name=type,proto3,enum=viewerdbpb.ViewerType" json:"type,omitempty"`
	// title
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// token
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*ViewerData_Graph
	//	*ViewerData_Json
	//	*ViewerData_Line
	//	*ViewerData_Multi
	//	*ViewerData_Pie
	//	*ViewerData_Scatter
	//	*ViewerData_Boxplot
	//	*ViewerData_Dtgame6
	//	*ViewerData_Scatter2
	//	*ViewerData_Boxplot2
	//	*ViewerData_Boxplot3
	Data                 isViewerData_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ViewerData) Reset()         { *m = ViewerData{} }
func (m *ViewerData) String() string { return proto.CompactTextString(m) }
func (*ViewerData) ProtoMessage()    {}
func (*ViewerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_22be9bcaf08cea01, []int{22}
}
func (m *ViewerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewerData.Unmarshal(m, b)
}
func (m *ViewerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewerData.Marshal(b, m, deterministic)
}
func (dst *ViewerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewerData.Merge(dst, src)
}
func (m *ViewerData) XXX_Size() int {
	return xxx_messageInfo_ViewerData.Size(m)
}
func (m *ViewerData) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewerData.DiscardUnknown(m)
}

var xxx_messageInfo_ViewerData proto.InternalMessageInfo

type isViewerData_Data interface {
	isViewerData_Data()
}

type ViewerData_Graph struct {
	Graph *GraphData `protobuf:"bytes,1000,opt,name=graph,proto3,oneof"`
}
type ViewerData_Json struct {
	Json *JSONData `protobuf:"bytes,1001,opt,name=json,proto3,oneof"`
}
type ViewerData_Line struct {
	Line *LineData `protobuf:"bytes,1002,opt,name=line,proto3,oneof"`
}
type ViewerData_Multi struct {
	Multi *MultiData `protobuf:"bytes,1003,opt,name=multi,proto3,oneof"`
}
type ViewerData_Pie struct {
	Pie *PieData `protobuf:"bytes,1004,opt,name=pie,proto3,oneof"`
}
type ViewerData_Scatter struct {
	Scatter *ScatterData `protobuf:"bytes,1005,opt,name=scatter,proto3,oneof"`
}
type ViewerData_Boxplot struct {
	Boxplot *BoxplotData `protobuf:"bytes,1006,opt,name=boxplot,proto3,oneof"`
}
type ViewerData_Dtgame6 struct {
	Dtgame6 *DTGame6Data `protobuf:"bytes,1007,opt,name=dtgame6,proto3,oneof"`
}
type ViewerData_Scatter2 struct {
	Scatter2 *Scatter2Data `protobuf:"bytes,1008,opt,name=scatter2,proto3,oneof"`
}
type ViewerData_Boxplot2 struct {
	Boxplot2 *Boxplot2Data `protobuf:"bytes,1009,opt,name=boxplot2,proto3,oneof"`
}
type ViewerData_Boxplot3 struct {
	Boxplot3 *Boxplot3Data `protobuf:"bytes,1010,opt,name=boxplot3,proto3,oneof"`
}

func (*ViewerData_Graph) isViewerData_Data()    {}
func (*ViewerData_Json) isViewerData_Data()     {}
func (*ViewerData_Line) isViewerData_Data()     {}
func (*ViewerData_Multi) isViewerData_Data()    {}
func (*ViewerData_Pie) isViewerData_Data()      {}
func (*ViewerData_Scatter) isViewerData_Data()  {}
func (*ViewerData_Boxplot) isViewerData_Data()  {}
func (*ViewerData_Dtgame6) isViewerData_Data()  {}
func (*ViewerData_Scatter2) isViewerData_Data() {}
func (*ViewerData_Boxplot2) isViewerData_Data() {}
func (*ViewerData_Boxplot3) isViewerData_Data() {}

func (m *ViewerData) GetData() isViewerData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ViewerData) GetType() ViewerType {
	if m != nil {
		return m.Type
	}
	return ViewerType_EMPTY
}

func (m *ViewerData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ViewerData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ViewerData) GetGraph() *GraphData {
	if x, ok := m.GetData().(*ViewerData_Graph); ok {
		return x.Graph
	}
	return nil
}

func (m *ViewerData) GetJson() *JSONData {
	if x, ok := m.GetData().(*ViewerData_Json); ok {
		return x.Json
	}
	return nil
}

func (m *ViewerData) GetLine() *LineData {
	if x, ok := m.GetData().(*ViewerData_Line); ok {
		return x.Line
	}
	return nil
}

func (m *ViewerData) GetMulti() *MultiData {
	if x, ok := m.GetData().(*ViewerData_Multi); ok {
		return x.Multi
	}
	return nil
}

func (m *ViewerData) GetPie() *PieData {
	if x, ok := m.GetData().(*ViewerData_Pie); ok {
		return x.Pie
	}
	return nil
}

func (m *ViewerData) GetScatter() *ScatterData {
	if x, ok := m.GetData().(*ViewerData_Scatter); ok {
		return x.Scatter
	}
	return nil
}

func (m *ViewerData) GetBoxplot() *BoxplotData {
	if x, ok := m.GetData().(*ViewerData_Boxplot); ok {
		return x.Boxplot
	}
	return nil
}

func (m *ViewerData) GetDtgame6() *DTGame6Data {
	if x, ok := m.GetData().(*ViewerData_Dtgame6); ok {
		return x.Dtgame6
	}
	return nil
}

func (m *ViewerData) GetScatter2() *Scatter2Data {
	if x, ok := m.GetData().(*ViewerData_Scatter2); ok {
		return x.Scatter2
	}
	return nil
}

func (m *ViewerData) GetBoxplot2() *Boxplot2Data {
	if x, ok := m.GetData().(*ViewerData_Boxplot2); ok {
		return x.Boxplot2
	}
	return nil
}

func (m *ViewerData) GetBoxplot3() *Boxplot3Data {
	if x, ok := m.GetData().(*ViewerData_Boxplot3); ok {
		return x.Boxplot3
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ViewerData) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ViewerData_OneofMarshaler, _ViewerData_OneofUnmarshaler, _ViewerData_OneofSizer, []interface{}{
		(*ViewerData_Graph)(nil),
		(*ViewerData_Json)(nil),
		(*ViewerData_Line)(nil),
		(*ViewerData_Multi)(nil),
		(*ViewerData_Pie)(nil),
		(*ViewerData_Scatter)(nil),
		(*ViewerData_Boxplot)(nil),
		(*ViewerData_Dtgame6)(nil),
		(*ViewerData_Scatter2)(nil),
		(*ViewerData_Boxplot2)(nil),
		(*ViewerData_Boxplot3)(nil),
	}
}

func _ViewerData_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ViewerData)
	// data
	switch x := m.Data.(type) {
	case *ViewerData_Graph:
		b.EncodeVarint(1000<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Graph); err != nil {
			return err
		}
	case *ViewerData_Json:
		b.EncodeVarint(1001<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Json); err != nil {
			return err
		}
	case *ViewerData_Line:
		b.EncodeVarint(1002<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Line); err != nil {
			return err
		}
	case *ViewerData_Multi:
		b.EncodeVarint(1003<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Multi); err != nil {
			return err
		}
	case *ViewerData_Pie:
		b.EncodeVarint(1004<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Pie); err != nil {
			return err
		}
	case *ViewerData_Scatter:
		b.EncodeVarint(1005<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Scatter); err != nil {
			return err
		}
	case *ViewerData_Boxplot:
		b.EncodeVarint(1006<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Boxplot); err != nil {
			return err
		}
	case *ViewerData_Dtgame6:
		b.EncodeVarint(1007<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Dtgame6); err != nil {
			return err
		}
	case *ViewerData_Scatter2:
		b.EncodeVarint(1008<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Scatter2); err != nil {
			return err
		}
	case *ViewerData_Boxplot2:
		b.EncodeVarint(1009<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Boxplot2); err != nil {
			return err
		}
	case *ViewerData_Boxplot3:
		b.EncodeVarint(1010<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Boxplot3); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ViewerData.Data has unexpected type %T", x)
	}
	return nil
}

func _ViewerData_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ViewerData)
	switch tag {
	case 1000: // data.graph
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GraphData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Graph{msg}
		return true, err
	case 1001: // data.json
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JSONData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Json{msg}
		return true, err
	case 1002: // data.line
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LineData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Line{msg}
		return true, err
	case 1003: // data.multi
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MultiData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Multi{msg}
		return true, err
	case 1004: // data.pie
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PieData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Pie{msg}
		return true, err
	case 1005: // data.scatter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ScatterData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Scatter{msg}
		return true, err
	case 1006: // data.boxplot
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoxplotData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Boxplot{msg}
		return true, err
	case 1007: // data.dtgame6
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DTGame6Data)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Dtgame6{msg}
		return true, err
	case 1008: // data.scatter2
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Scatter2Data)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Scatter2{msg}
		return true, err
	case 1009: // data.boxplot2
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Boxplot2Data)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Boxplot2{msg}
		return true, err
	case 1010: // data.boxplot3
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Boxplot3Data)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Boxplot3{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ViewerData_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ViewerData)
	// data
	switch x := m.Data.(type) {
	case *ViewerData_Graph:
		s := proto.Size(x.Graph)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Json:
		s := proto.Size(x.Json)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Line:
		s := proto.Size(x.Line)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Multi:
		s := proto.Size(x.Multi)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Pie:
		s := proto.Size(x.Pie)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Scatter:
		s := proto.Size(x.Scatter)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Boxplot:
		s := proto.Size(x.Boxplot)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Dtgame6:
		s := proto.Size(x.Dtgame6)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Scatter2:
		s := proto.Size(x.Scatter2)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Boxplot2:
		s := proto.Size(x.Boxplot2)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Boxplot3:
		s := proto.Size(x.Boxplot3)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*GraphNode)(nil), "viewerdbpb.GraphNode")
	proto.RegisterType((*GraphLink)(nil), "viewerdbpb.GraphLink")
	proto.RegisterType((*GraphData)(nil), "viewerdbpb.GraphData")
	proto.RegisterType((*JSONData)(nil), "viewerdbpb.JSONData")
	proto.RegisterType((*LineSeriesData)(nil), "viewerdbpb.LineSeriesData")
	proto.RegisterType((*LineData)(nil), "viewerdbpb.LineData")
	proto.RegisterType((*MultiData)(nil), "viewerdbpb.MultiData")
	proto.RegisterType((*PieDataInfo)(nil), "viewerdbpb.PieDataInfo")
	proto.RegisterType((*PieData)(nil), "viewerdbpb.PieData")
	proto.RegisterType((*ScatterNode)(nil), "viewerdbpb.ScatterNode")
	proto.RegisterType((*ScatterData)(nil), "viewerdbpb.ScatterData")
	proto.RegisterType((*Scatter2Data)(nil), "viewerdbpb.Scatter2Data")
	proto.RegisterType((*Dataset)(nil), "viewerdbpb.Dataset")
	proto.RegisterType((*BoxplotNode)(nil), "viewerdbpb.BoxplotNode")
	proto.RegisterType((*BoxplotData)(nil), "viewerdbpb.BoxplotData")
	proto.RegisterType((*Boxplot2Data)(nil), "viewerdbpb.Boxplot2Data")
	proto.RegisterType((*Boxplot3)(nil), "viewerdbpb.Boxplot3")
	proto.RegisterType((*Boxplot3Data)(nil), "viewerdbpb.Boxplot3Data")
	proto.RegisterMapType((map[string]*Dataset)(nil), "viewerdbpb.Boxplot3Data.DatasetsEntry")
	proto.RegisterType((*DTGame6List)(nil), "viewerdbpb.DTGame6List")
	proto.RegisterType((*DTGame6Pos)(nil), "viewerdbpb.DTGame6Pos")
	proto.RegisterType((*DTGame6Result)(nil), "viewerdbpb.DTGame6Result")
	proto.RegisterType((*DTGame6Data)(nil), "viewerdbpb.DTGame6Data")
	proto.RegisterType((*ViewerData)(nil), "viewerdbpb.ViewerData")
	proto.RegisterEnum("viewerdbpb.ViewerType", ViewerType_name, ViewerType_value)
	proto.RegisterEnum("viewerdbpb.ValueType", ValueType_name, ValueType_value)
	proto.RegisterEnum("viewerdbpb.DTGame6ArrayType", DTGame6ArrayType_name, DTGame6ArrayType_value)
}

func init() { proto.RegisterFile("viewer.proto", fileDescriptor_viewer_22be9bcaf08cea01) }

var fileDescriptor_viewer_22be9bcaf08cea01 = []byte{
	// 1459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0x4b, 0x6f, 0xdb, 0x46,
	0x10, 0x36, 0x45, 0x51, 0x8f, 0x91, 0x63, 0x30, 0x6c, 0x9a, 0x6e, 0x02, 0xa3, 0x15, 0x58, 0xa0,
	0x51, 0x1c, 0xc0, 0x2d, 0x24, 0x43, 0x6d, 0x7a, 0xb3, 0x63, 0xc5, 0x56, 0x20, 0xc9, 0xc2, 0x5a,
	0x76, 0x9a, 0x53, 0x41, 0x85, 0x5b, 0x87, 0x35, 0x4d, 0x1a, 0x24, 0xed, 0x48, 0xf9, 0x2b, 0x45,
	0xef, 0xfd, 0x29, 0x6d, 0xda, 0x9f, 0x50, 0xf4, 0xd4, 0x43, 0xdf, 0xaf, 0x6b, 0x0f, 0x2d, 0x66,
	0x77, 0x49, 0xae, 0x6c, 0xba, 0x39, 0xf7, 0xb6, 0x33, 0xfc, 0x66, 0xe7, 0xf5, 0xcd, 0xee, 0x12,
	0x96, 0xcf, 0x3d, 0xf6, 0x9c, 0x45, 0xeb, 0xa7, 0x51, 0x98, 0x84, 0x16, 0x08, 0xc9, 0x9d, 0x9e,
	0x4e, 0xed, 0x8f, 0xa1, 0xbe, 0x13, 0x39, 0xa7, 0xcf, 0x46, 0xa1, 0xcb, 0xac, 0x15, 0x28, 0x79,
	0x2e, 0xd1, 0x9a, 0x5a, 0xcb, 0xa0, 0x25, 0xcf, 0xb5, 0x2c, 0x28, 0x07, 0xce, 0x09, 0x23, 0xa5,
	0xa6, 0xd6, 0xaa, 0x53, 0xbe, 0x46, 0x5d, 0xec, 0xbd, 0x60, 0x44, 0xe7, 0x28, 0xbe, 0xb6, 0x6e,
	0x43, 0xed, 0xa9, 0x93, 0xb0, 0xa3, 0x30, 0x9a, 0x93, 0x32, 0xc7, 0x66, 0xb2, 0xdd, 0x93, 0x0e,
	0x06, 0x5e, 0x70, 0x6c, 0x99, 0xa0, 0xc7, 0xd1, 0x53, 0xe9, 0x01, 0x97, 0xb8, 0x9d, 0xcb, 0xe2,
	0x84, 0xbb, 0x30, 0x28, 0x5f, 0x17, 0xb9, 0xb0, 0x99, 0xdc, 0x66, 0xdb, 0x49, 0x1c, 0xeb, 0x1e,
	0x18, 0x41, 0xe8, 0xb2, 0x98, 0x68, 0x4d, 0xbd, 0xd5, 0x68, 0xbf, 0xbe, 0x9e, 0x27, 0xb4, 0x9e,
	0x65, 0x43, 0x05, 0x06, 0xc1, 0xbe, 0x17, 0x1c, 0xc7, 0xa4, 0x74, 0x05, 0x18, 0x23, 0xa3, 0x02,
	0x63, 0xaf, 0x42, 0xed, 0xd1, 0xfe, 0xde, 0x88, 0x7b, 0xc1, 0x60, 0x93, 0x88, 0x07, 0x5b, 0xa7,
	0xb8, 0xb4, 0x5f, 0xc0, 0xca, 0xc0, 0x0b, 0xd8, 0x3e, 0x8b, 0x3c, 0x16, 0x73, 0x4c, 0x5a, 0x21,
	0x4d, 0xa9, 0xd0, 0x2a, 0xd4, 0xcf, 0x1d, 0x7f, 0x3f, 0x89, 0xbc, 0xe0, 0x88, 0x3b, 0xad, 0xd3,
	0x5c, 0x81, 0xb5, 0x3a, 0x77, 0xfc, 0x7e, 0x90, 0x74, 0xda, 0x44, 0x6f, 0xea, 0x2d, 0x83, 0x66,
	0x72, 0xfe, 0xad, 0xbb, 0x41, 0xca, 0x4d, 0xbd, 0xa5, 0xd3, 0x4c, 0xb6, 0xbf, 0xd5, 0xa0, 0x86,
	0xce, 0xb9, 0xdb, 0x55, 0xa8, 0xcf, 0x36, 0x67, 0x5e, 0x3c, 0x99, 0x9f, 0xa6, 0xbe, 0x73, 0x85,
	0xd5, 0x84, 0x06, 0x17, 0x16, 0x42, 0x50, 0x55, 0xd6, 0x9b, 0x00, 0x5c, 0x54, 0xc3, 0x50, 0x34,
	0xea, 0xf7, 0x2c, 0x14, 0x45, 0x83, 0xfe, 0xe7, 0x99, 0x7f, 0x57, 0xf8, 0xcf, 0x14, 0x56, 0x1b,
	0x2a, 0x31, 0x2f, 0x11, 0x61, 0xbc, 0xe4, 0xb7, 0xd5, 0x92, 0x2f, 0x16, 0x90, 0x4a, 0xa4, 0xfd,
	0x36, 0xd4, 0x87, 0x67, 0x7e, 0xe2, 0xf1, 0xf4, 0x6e, 0x42, 0x25, 0x09, 0x8f, 0x59, 0x20, 0x1a,
	0x5c, 0xa7, 0x52, 0xb2, 0x9f, 0x40, 0x63, 0xec, 0xf1, 0x0a, 0xf4, 0x83, 0x4f, 0xc2, 0xc2, 0xe2,
	0xab, 0xe5, 0x15, 0x9c, 0x2a, 0x2e, 0x2f, 0x72, 0x4b, 0x2d, 0xef, 0x23, 0xa8, 0xca, 0xad, 0x0b,
	0xb7, 0xbd, 0x07, 0x65, 0xd7, 0x49, 0x1c, 0xc9, 0xa1, 0x37, 0xd4, 0x84, 0x94, 0x88, 0x28, 0x07,
	0xd9, 0x27, 0xd0, 0xd8, 0x7f, 0xea, 0x24, 0x09, 0x8b, 0xf8, 0x54, 0xdd, 0x84, 0xca, 0x4c, 0x04,
	0x24, 0x78, 0x2f, 0xa5, 0x54, 0xdf, 0xdd, 0xe0, 0x81, 0xea, 0x54, 0x4a, 0xa8, 0x9f, 0x0b, 0xbc,
	0x2b, 0xf0, 0xf3, 0x0c, 0x3f, 0x17, 0x78, 0x26, 0xf0, 0x42, 0xb2, 0xbf, 0xd0, 0x32, 0x7f, 0xe9,
	0x74, 0xcc, 0x32, 0x62, 0xac, 0x2c, 0x12, 0xfe, 0xd0, 0xf1, 0xcf, 0x18, 0x7e, 0xa4, 0x02, 0x83,
	0xe0, 0x39, 0x07, 0x97, 0xfe, 0x13, 0x3c, 0x97, 0x60, 0x51, 0x05, 0xfd, 0x72, 0x15, 0x94, 0x84,
	0x45, 0x15, 0xb2, 0x32, 0x96, 0xf3, 0x32, 0xda, 0xf7, 0x61, 0x59, 0x02, 0xdb, 0x3c, 0xd4, 0xbb,
	0xa0, 0xfb, 0x71, 0x22, 0xc7, 0xb8, 0x68, 0x3f, 0xce, 0x11, 0xc4, 0xd8, 0xdf, 0x6b, 0x50, 0x45,
	0x29, 0x66, 0xfc, 0x80, 0x18, 0x29, 0x1d, 0xc2, 0xb5, 0xf5, 0x2e, 0x54, 0xcf, 0x1d, 0xff, 0xd5,
	0xa9, 0xa4, 0x28, 0x64, 0x83, 0x13, 0x45, 0x0b, 0x83, 0x98, 0xca, 0xf9, 0xb7, 0x7c, 0x10, 0x53,
	0x19, 0x67, 0xc3, 0x89, 0xa2, 0x87, 0x7e, 0xe8, 0xa0, 0xa5, 0xd1, 0xd4, 0x5b, 0x25, 0xaa, 0x68,
	0xd4, 0xef, 0xdd, 0x0d, 0x52, 0x69, 0xea, 0x2d, 0x8d, 0x2a, 0x1a, 0x9c, 0x1d, 0x27, 0x8a, 0xe4,
	0x6c, 0x56, 0xc5, 0xf1, 0x90, 0x29, 0xec, 0x97, 0x1a, 0x34, 0xb6, 0xc2, 0xd9, 0xa9, 0x1f, 0x26,
	0x9c, 0x3c, 0xff, 0xe7, 0x54, 0xed, 0xc3, 0x2c, 0x17, 0x49, 0x4c, 0x41, 0x9f, 0x82, 0x76, 0x2b,
	0x29, 0x4b, 0xfa, 0xa8, 0x77, 0x4a, 0xe9, 0xc2, 0x9d, 0x72, 0x1f, 0x96, 0xa5, 0xc1, 0xab, 0x68,
	0xa4, 0xb8, 0x17, 0x34, 0xda, 0x85, 0x9a, 0xd4, 0x75, 0x16, 0x5c, 0x68, 0x8b, 0x2e, 0xf0, 0x0c,
	0x75, 0x05, 0xdb, 0x46, 0xe2, 0x06, 0xe4, 0x67, 0xa8, 0xa2, 0xb2, 0xff, 0xd1, 0xb2, 0x28, 0x3a,
	0x3c, 0x8a, 0x2d, 0xa8, 0xc9, 0xef, 0xe9, 0xc5, 0xf4, 0x4e, 0x41, 0x28, 0x1c, 0xbb, 0x2e, 0x99,
	0x1c, 0xf7, 0x82, 0x24, 0x9a, 0xd3, 0xcc, 0xce, 0x7a, 0x0f, 0x6a, 0x53, 0x81, 0x4b, 0xef, 0xab,
	0x1b, 0x45, 0x7b, 0xd0, 0x0c, 0x65, 0xdd, 0x81, 0xf2, 0xec, 0xd0, 0xf1, 0xf9, 0x81, 0xd6, 0x68,
	0xbf, 0xa6, 0xa2, 0xa5, 0x13, 0xca, 0x01, 0xb7, 0xc7, 0x70, 0x6d, 0xc1, 0x2b, 0xde, 0x6f, 0xc7,
	0x2c, 0xcd, 0x1c, 0x97, 0xd6, 0x5d, 0x30, 0xce, 0x91, 0x3d, 0xbc, 0xe0, 0x57, 0x6c, 0x26, 0x10,
	0x1f, 0x96, 0x3e, 0xd0, 0xec, 0xb7, 0xa0, 0xb1, 0x3d, 0xd9, 0x71, 0x4e, 0x58, 0x77, 0xe0, 0xc5,
	0x09, 0xee, 0xe7, 0x44, 0x11, 0x4f, 0xdd, 0xa0, 0xb8, 0xb4, 0x5b, 0x00, 0x12, 0x30, 0x0e, 0x63,
	0x6b, 0x19, 0xb4, 0x99, 0x3c, 0x02, 0xb5, 0x19, 0x4a, 0x73, 0x79, 0x42, 0x6b, 0x73, 0xfb, 0x6f,
	0x0d, 0xae, 0x49, 0x28, 0x65, 0xf1, 0x99, 0xcf, 0x67, 0x3c, 0xc9, 0x6f, 0x37, 0xbe, 0x46, 0x0f,
	0x53, 0x96, 0xbe, 0x15, 0x70, 0x69, 0x11, 0xa8, 0x46, 0xcc, 0xf1, 0xb7, 0x58, 0x22, 0x5f, 0x0b,
	0xa9, 0x88, 0x5f, 0xa6, 0x4e, 0xcc, 0x86, 0x67, 0x3e, 0x3f, 0x81, 0x0c, 0x9a, 0x8a, 0xb8, 0xcb,
	0x73, 0x2f, 0x20, 0x86, 0xd8, 0xe5, 0xb9, 0x17, 0xa4, 0xbb, 0x3c, 0xf6, 0x02, 0x52, 0xc9, 0x77,
	0x79, 0xec, 0x05, 0xc8, 0xf0, 0x69, 0x18, 0x9c, 0xc5, 0xe3, 0x08, 0x1f, 0x24, 0x55, 0xfe, 0x51,
	0xd1, 0x20, 0x85, 0xc2, 0xe4, 0x19, 0x8b, 0xd0, 0x4d, 0x4d, 0x5c, 0x37, 0xa9, 0x6c, 0xb5, 0x40,
	0x3f, 0x0d, 0x63, 0xe2, 0xf2, 0x36, 0xde, 0x5c, 0xa8, 0x65, 0x56, 0x14, 0x8a, 0x10, 0xfb, 0xbb,
	0x52, 0x56, 0xc9, 0x6d, 0xc9, 0xfd, 0x23, 0xe7, 0x84, 0x3d, 0x08, 0xdd, 0x34, 0xff, 0x4c, 0xc6,
	0x88, 0x70, 0x3d, 0x0c, 0xdd, 0x33, 0x3f, 0x7d, 0x99, 0x29, 0x1a, 0xfc, 0xee, 0x7b, 0x71, 0x32,
	0x76, 0x22, 0x16, 0x24, 0x7c, 0xda, 0xeb, 0x54, 0xd1, 0x58, 0x5d, 0xa8, 0x3a, 0x51, 0x94, 0x5d,
	0xdc, 0x2b, 0xed, 0xd5, 0x82, 0xc8, 0x36, 0xa3, 0xc8, 0x99, 0x8b, 0x33, 0x44, 0x82, 0x71, 0xc6,
	0xb0, 0xbb, 0xec, 0xf2, 0x8c, 0x29, 0x1c, 0xe0, 0x6d, 0xb7, 0xae, 0x8b, 0x36, 0x7d, 0xa9, 0xe5,
	0x7d, 0xba, 0x95, 0xf7, 0xe9, 0x2b, 0x6d, 0xb1, 0x51, 0xd7, 0x45, 0x3b, 0x5e, 0x6a, 0x79, 0x3f,
	0x6e, 0xe5, 0xfd, 0xf8, 0x5a, 0x5b, 0x6c, 0xc8, 0x06, 0x7e, 0x42, 0x82, 0xc4, 0xe4, 0x1b, 0x31,
	0x64, 0xb7, 0x0a, 0x62, 0x11, 0x1c, 0xa2, 0x29, 0xd4, 0xfe, 0xdc, 0x00, 0x38, 0xe4, 0x28, 0x5e,
	0xdf, 0x35, 0x85, 0x5b, 0x2b, 0x8b, 0xad, 0x11, 0x28, 0x9e, 0xba, 0xe0, 0xdc, 0x0d, 0x30, 0x12,
	0x2f, 0xc9, 0x4a, 0x2d, 0x04, 0xae, 0xc5, 0x37, 0x09, 0x67, 0x1d, 0x6a, 0x51, 0xb0, 0xd6, 0xc1,
	0x38, 0xc2, 0x17, 0x25, 0xf9, 0xa1, 0xca, 0x07, 0xe8, 0xf2, 0x5b, 0x13, 0xdd, 0xef, 0x2e, 0x51,
	0x01, 0xc3, 0x03, 0xf1, 0xd3, 0x38, 0x0c, 0xc8, 0x8f, 0x02, 0xbe, 0x30, 0xea, 0xe9, 0x33, 0x74,
	0x77, 0x89, 0x72, 0x10, 0x82, 0x7d, 0x2f, 0x60, 0xe4, 0xa7, 0x02, 0x70, 0xfa, 0x30, 0x44, 0x30,
	0x82, 0x30, 0x92, 0x13, 0x7c, 0x4e, 0x91, 0x9f, 0x0b, 0x22, 0xc9, 0x1e, 0x5a, 0x18, 0x09, 0x87,
	0x71, 0xae, 0x7a, 0x8c, 0xfc, 0x52, 0xbd, 0x3c, 0xf8, 0xf2, 0x7d, 0xb3, 0xbb, 0x44, 0x11, 0x82,
	0x0d, 0x88, 0xc5, 0xdd, 0x4c, 0x7e, 0x15, 0xe8, 0xab, 0xee, 0xed, 0xdd, 0x25, 0x9a, 0x42, 0xd1,
	0x4a, 0x9e, 0x58, 0xe4, 0xb7, 0x02, 0x2b, 0xe5, 0x98, 0x46, 0x2b, 0x09, 0x45, 0x2b, 0x37, 0x41,
	0x6e, 0x77, 0xc9, 0xef, 0x05, 0x56, 0xca, 0xc8, 0xa0, 0x95, 0x84, 0x5a, 0xef, 0x43, 0x4d, 0xba,
	0x6d, 0x93, 0x3f, 0x84, 0x19, 0x29, 0x08, 0xb1, 0x2d, 0xed, 0x32, 0x30, 0x1a, 0x4a, 0xcf, 0x6d,
	0xf2, 0x67, 0x81, 0xa1, 0x7a, 0xe7, 0xa0, 0x61, 0x0a, 0x56, 0x0c, 0x3b, 0xe4, 0xaf, 0xab, 0x0d,
	0x3b, 0x17, 0x0c, 0x3b, 0x5b, 0x15, 0x71, 0x23, 0xae, 0x7d, 0xa6, 0xa5, 0xfc, 0xe4, 0xb3, 0x56,
	0x07, 0xa3, 0x37, 0x1c, 0x4f, 0x9e, 0x98, 0x4b, 0xb8, 0xdc, 0xa1, 0x9b, 0xe3, 0x5d, 0x53, 0xb3,
	0x6a, 0x50, 0x46, 0x52, 0x98, 0x25, 0x5c, 0x0d, 0xfa, 0xa3, 0x9e, 0xa9, 0xe3, 0xe7, 0xe1, 0xc1,
	0x60, 0xd2, 0x37, 0xcb, 0x56, 0x15, 0xf4, 0x71, 0xbf, 0x67, 0x1a, 0x56, 0x03, 0xaa, 0xfb, 0x0f,
	0x36, 0x27, 0x93, 0x1e, 0x35, 0x2b, 0x28, 0x6c, 0xed, 0x7d, 0x34, 0x1e, 0xec, 0x4d, 0xcc, 0x2a,
	0x0a, 0xdb, 0x93, 0x9d, 0xcd, 0x61, 0xaf, 0x6b, 0xd6, 0xac, 0x65, 0xa8, 0x49, 0x58, 0xdb, 0xac,
	0xa3, 0x24, 0x71, 0x6d, 0x13, 0x14, 0xa9, 0x63, 0x36, 0xd6, 0x0e, 0xa0, 0x9e, 0x3d, 0x2a, 0xf0,
	0xd3, 0xe8, 0x60, 0x30, 0x98, 0x3c, 0x19, 0xf7, 0x44, 0x78, 0xfd, 0xd1, 0xa4, 0xd3, 0x36, 0x35,
	0xb9, 0xec, 0x6e, 0x98, 0x25, 0xf4, 0xf3, 0x70, 0xb0, 0xb7, 0x89, 0x7a, 0x3d, 0x13, 0xba, 0x1b,
	0x66, 0xd9, 0x02, 0xa8, 0xec, 0x4f, 0x68, 0x7f, 0xb4, 0x63, 0x1a, 0x6b, 0x77, 0xc0, 0xbc, 0x78,
	0xdc, 0x60, 0x12, 0x74, 0xef, 0xb1, 0xb9, 0x84, 0xc0, 0x07, 0x7b, 0x83, 0x83, 0xe1, 0xc8, 0xd4,
	0xa6, 0x15, 0xfe, 0xdb, 0xda, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x66, 0x36, 0x75, 0xd3, 0xc6,
	0x0e, 0x00, 0x00,
}
