// Code generated by protoc-gen-go. DO NOT EDIT.
// source: viewer.proto

package viewerdbpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ViewerType - Viewer type
//            - 数据类型
type ViewerType int32

const (
	ViewerType_EMPTY   ViewerType = 0
	ViewerType_GRAPH   ViewerType = 1
	ViewerType_JSON    ViewerType = 2
	ViewerType_LINE    ViewerType = 3
	ViewerType_MULTI   ViewerType = 4
	ViewerType_PIE     ViewerType = 5
	ViewerType_SCATTER ViewerType = 6
	ViewerType_BOXPLOT ViewerType = 7
)

var ViewerType_name = map[int32]string{
	0: "EMPTY",
	1: "GRAPH",
	2: "JSON",
	3: "LINE",
	4: "MULTI",
	5: "PIE",
	6: "SCATTER",
	7: "BOXPLOT",
}
var ViewerType_value = map[string]int32{
	"EMPTY":   0,
	"GRAPH":   1,
	"JSON":    2,
	"LINE":    3,
	"MULTI":   4,
	"PIE":     5,
	"SCATTER": 6,
	"BOXPLOT": 7,
}

func (x ViewerType) String() string {
	return proto.EnumName(ViewerType_name, int32(x))
}
func (ViewerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{0}
}

// ValueType - Value type
//           - 数据类型
type ValueType int32

const (
	ValueType_STRING  ValueType = 0
	ValueType_INT32   ValueType = 1
	ValueType_INT64   ValueType = 2
	ValueType_FLOAT32 ValueType = 3
	ValueType_FLOAT64 ValueType = 4
)

var ValueType_name = map[int32]string{
	0: "STRING",
	1: "INT32",
	2: "INT64",
	3: "FLOAT32",
	4: "FLOAT64",
}
var ValueType_value = map[string]int32{
	"STRING":  0,
	"INT32":   1,
	"INT64":   2,
	"FLOAT32": 3,
	"FLOAT64": 4,
}

func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{1}
}

// GraphNode - Graph node
//           - 图节点
type GraphNode struct {
	// id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// size
	Size int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// category
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphNode) Reset()         { *m = GraphNode{} }
func (m *GraphNode) String() string { return proto.CompactTextString(m) }
func (*GraphNode) ProtoMessage()    {}
func (*GraphNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{0}
}
func (m *GraphNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphNode.Unmarshal(m, b)
}
func (m *GraphNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphNode.Marshal(b, m, deterministic)
}
func (dst *GraphNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphNode.Merge(dst, src)
}
func (m *GraphNode) XXX_Size() int {
	return xxx_messageInfo_GraphNode.Size(m)
}
func (m *GraphNode) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphNode.DiscardUnknown(m)
}

var xxx_messageInfo_GraphNode proto.InternalMessageInfo

func (m *GraphNode) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GraphNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphNode) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GraphNode) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

// GraphLink - Graph link info
//           - 图节点连接关系
type GraphLink struct {
	// src
	Src int32 `protobuf:"varint,1,opt,name=src,proto3" json:"src,omitempty"`
	// dest
	Dest int32 `protobuf:"varint,2,opt,name=dest,proto3" json:"dest,omitempty"`
	// size
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphLink) Reset()         { *m = GraphLink{} }
func (m *GraphLink) String() string { return proto.CompactTextString(m) }
func (*GraphLink) ProtoMessage()    {}
func (*GraphLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{1}
}
func (m *GraphLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphLink.Unmarshal(m, b)
}
func (m *GraphLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphLink.Marshal(b, m, deterministic)
}
func (dst *GraphLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphLink.Merge(dst, src)
}
func (m *GraphLink) XXX_Size() int {
	return xxx_messageInfo_GraphLink.Size(m)
}
func (m *GraphLink) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphLink.DiscardUnknown(m)
}

var xxx_messageInfo_GraphLink proto.InternalMessageInfo

func (m *GraphLink) GetSrc() int32 {
	if m != nil {
		return m.Src
	}
	return 0
}

func (m *GraphLink) GetDest() int32 {
	if m != nil {
		return m.Dest
	}
	return 0
}

func (m *GraphLink) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

// GraphData - Graph data
//           - 图节点完整数据
type GraphData struct {
	// nodes
	Nodes []*GraphNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// links
	Links                []*GraphLink `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GraphData) Reset()         { *m = GraphData{} }
func (m *GraphData) String() string { return proto.CompactTextString(m) }
func (*GraphData) ProtoMessage()    {}
func (*GraphData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{2}
}
func (m *GraphData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphData.Unmarshal(m, b)
}
func (m *GraphData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphData.Marshal(b, m, deterministic)
}
func (dst *GraphData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphData.Merge(dst, src)
}
func (m *GraphData) XXX_Size() int {
	return xxx_messageInfo_GraphData.Size(m)
}
func (m *GraphData) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphData.DiscardUnknown(m)
}

var xxx_messageInfo_GraphData proto.InternalMessageInfo

func (m *GraphData) GetNodes() []*GraphNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *GraphData) GetLinks() []*GraphLink {
	if m != nil {
		return m.Links
	}
	return nil
}

// JSONData - JSON data
//          - json格式的数据
type JSONData struct {
	// string for json
	Str                  string   `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JSONData) Reset()         { *m = JSONData{} }
func (m *JSONData) String() string { return proto.CompactTextString(m) }
func (*JSONData) ProtoMessage()    {}
func (*JSONData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{3}
}
func (m *JSONData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSONData.Unmarshal(m, b)
}
func (m *JSONData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSONData.Marshal(b, m, deterministic)
}
func (dst *JSONData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSONData.Merge(dst, src)
}
func (m *JSONData) XXX_Size() int {
	return xxx_messageInfo_JSONData.Size(m)
}
func (m *JSONData) XXX_DiscardUnknown() {
	xxx_messageInfo_JSONData.DiscardUnknown(m)
}

var xxx_messageInfo_JSONData proto.InternalMessageInfo

func (m *JSONData) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

// LineSeriesData - Line series data
//                - 折线图数据
type LineSeriesData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ValString            []string `protobuf:"bytes,2,rep,name=valString,proto3" json:"valString,omitempty"`
	ValInt32             []int32  `protobuf:"varint,3,rep,packed,name=valInt32,proto3" json:"valInt32,omitempty"`
	ValInt64             []int64  `protobuf:"varint,4,rep,packed,name=valInt64,proto3" json:"valInt64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LineSeriesData) Reset()         { *m = LineSeriesData{} }
func (m *LineSeriesData) String() string { return proto.CompactTextString(m) }
func (*LineSeriesData) ProtoMessage()    {}
func (*LineSeriesData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{4}
}
func (m *LineSeriesData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineSeriesData.Unmarshal(m, b)
}
func (m *LineSeriesData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineSeriesData.Marshal(b, m, deterministic)
}
func (dst *LineSeriesData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineSeriesData.Merge(dst, src)
}
func (m *LineSeriesData) XXX_Size() int {
	return xxx_messageInfo_LineSeriesData.Size(m)
}
func (m *LineSeriesData) XXX_DiscardUnknown() {
	xxx_messageInfo_LineSeriesData.DiscardUnknown(m)
}

var xxx_messageInfo_LineSeriesData proto.InternalMessageInfo

func (m *LineSeriesData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LineSeriesData) GetValString() []string {
	if m != nil {
		return m.ValString
	}
	return nil
}

func (m *LineSeriesData) GetValInt32() []int32 {
	if m != nil {
		return m.ValInt32
	}
	return nil
}

func (m *LineSeriesData) GetValInt64() []int64 {
	if m != nil {
		return m.ValInt64
	}
	return nil
}

// LineData - Line data
//           - 折线图完整数据
type LineData struct {
	// xAxisType
	XAxisType string `protobuf:"bytes,1,opt,name=xAxisType,proto3" json:"xAxisType,omitempty"`
	// xAxisString
	XAxisString []string `protobuf:"bytes,2,rep,name=xAxisString,proto3" json:"xAxisString,omitempty"`
	// xAxisInt32
	XAxisInt32 []int32 `protobuf:"varint,3,rep,packed,name=xAxisInt32,proto3" json:"xAxisInt32,omitempty"`
	// xAxisInt64
	XAxisInt64 []int64 `protobuf:"varint,4,rep,packed,name=xAxisInt64,proto3" json:"xAxisInt64,omitempty"`
	// yAxisType
	YAxisType string `protobuf:"bytes,100,opt,name=yAxisType,proto3" json:"yAxisType,omitempty"`
	// xAxisData
	Series               []*LineSeriesData `protobuf:"bytes,101,rep,name=series,proto3" json:"series,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LineData) Reset()         { *m = LineData{} }
func (m *LineData) String() string { return proto.CompactTextString(m) }
func (*LineData) ProtoMessage()    {}
func (*LineData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{5}
}
func (m *LineData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineData.Unmarshal(m, b)
}
func (m *LineData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineData.Marshal(b, m, deterministic)
}
func (dst *LineData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineData.Merge(dst, src)
}
func (m *LineData) XXX_Size() int {
	return xxx_messageInfo_LineData.Size(m)
}
func (m *LineData) XXX_DiscardUnknown() {
	xxx_messageInfo_LineData.DiscardUnknown(m)
}

var xxx_messageInfo_LineData proto.InternalMessageInfo

func (m *LineData) GetXAxisType() string {
	if m != nil {
		return m.XAxisType
	}
	return ""
}

func (m *LineData) GetXAxisString() []string {
	if m != nil {
		return m.XAxisString
	}
	return nil
}

func (m *LineData) GetXAxisInt32() []int32 {
	if m != nil {
		return m.XAxisInt32
	}
	return nil
}

func (m *LineData) GetXAxisInt64() []int64 {
	if m != nil {
		return m.XAxisInt64
	}
	return nil
}

func (m *LineData) GetYAxisType() string {
	if m != nil {
		return m.YAxisType
	}
	return ""
}

func (m *LineData) GetSeries() []*LineSeriesData {
	if m != nil {
		return m.Series
	}
	return nil
}

// MultiData - Multi data
//           - 多数据模式完整数据
type MultiData struct {
	// tokens
	Tokens               []string `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiData) Reset()         { *m = MultiData{} }
func (m *MultiData) String() string { return proto.CompactTextString(m) }
func (*MultiData) ProtoMessage()    {}
func (*MultiData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{6}
}
func (m *MultiData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiData.Unmarshal(m, b)
}
func (m *MultiData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiData.Marshal(b, m, deterministic)
}
func (dst *MultiData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiData.Merge(dst, src)
}
func (m *MultiData) XXX_Size() int {
	return xxx_messageInfo_MultiData.Size(m)
}
func (m *MultiData) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiData.DiscardUnknown(m)
}

var xxx_messageInfo_MultiData proto.InternalMessageInfo

func (m *MultiData) GetTokens() []string {
	if m != nil {
		return m.Tokens
	}
	return nil
}

// PieDataInfo - Pie data info
//             - 饼图完整数据
type PieDataInfo struct {
	// name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// valInt32
	ValInt32 int32 `protobuf:"varint,2,opt,name=valInt32,proto3" json:"valInt32,omitempty"`
	// valInt64
	ValInt64             int64    `protobuf:"varint,3,opt,name=valInt64,proto3" json:"valInt64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieDataInfo) Reset()         { *m = PieDataInfo{} }
func (m *PieDataInfo) String() string { return proto.CompactTextString(m) }
func (*PieDataInfo) ProtoMessage()    {}
func (*PieDataInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{7}
}
func (m *PieDataInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieDataInfo.Unmarshal(m, b)
}
func (m *PieDataInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieDataInfo.Marshal(b, m, deterministic)
}
func (dst *PieDataInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieDataInfo.Merge(dst, src)
}
func (m *PieDataInfo) XXX_Size() int {
	return xxx_messageInfo_PieDataInfo.Size(m)
}
func (m *PieDataInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PieDataInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PieDataInfo proto.InternalMessageInfo

func (m *PieDataInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PieDataInfo) GetValInt32() int32 {
	if m != nil {
		return m.ValInt32
	}
	return 0
}

func (m *PieDataInfo) GetValInt64() int64 {
	if m != nil {
		return m.ValInt64
	}
	return 0
}

// PieData - Pie data
//         - 饼图完整数据
type PieData struct {
	// name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// tokens
	Data                 []*PieDataInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PieData) Reset()         { *m = PieData{} }
func (m *PieData) String() string { return proto.CompactTextString(m) }
func (*PieData) ProtoMessage()    {}
func (*PieData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{8}
}
func (m *PieData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieData.Unmarshal(m, b)
}
func (m *PieData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieData.Marshal(b, m, deterministic)
}
func (dst *PieData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieData.Merge(dst, src)
}
func (m *PieData) XXX_Size() int {
	return xxx_messageInfo_PieData.Size(m)
}
func (m *PieData) XXX_DiscardUnknown() {
	xxx_messageInfo_PieData.DiscardUnknown(m)
}

var xxx_messageInfo_PieData proto.InternalMessageInfo

func (m *PieData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PieData) GetData() []*PieDataInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

// ScatterNode - scatter node
//             - 散点图数据
type ScatterNode struct {
	// xInt32
	XInt32 int32 `protobuf:"varint,1,opt,name=xInt32,proto3" json:"xInt32,omitempty"`
	// xInt64
	XInt64 int64 `protobuf:"varint,2,opt,name=xInt64,proto3" json:"xInt64,omitempty"`
	// yInt32
	YInt32 int32 `protobuf:"varint,100,opt,name=yInt32,proto3" json:"yInt32,omitempty"`
	// xInt64
	YInt64               int64    `protobuf:"varint,101,opt,name=yInt64,proto3" json:"yInt64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScatterNode) Reset()         { *m = ScatterNode{} }
func (m *ScatterNode) String() string { return proto.CompactTextString(m) }
func (*ScatterNode) ProtoMessage()    {}
func (*ScatterNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{9}
}
func (m *ScatterNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScatterNode.Unmarshal(m, b)
}
func (m *ScatterNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScatterNode.Marshal(b, m, deterministic)
}
func (dst *ScatterNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScatterNode.Merge(dst, src)
}
func (m *ScatterNode) XXX_Size() int {
	return xxx_messageInfo_ScatterNode.Size(m)
}
func (m *ScatterNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ScatterNode.DiscardUnknown(m)
}

var xxx_messageInfo_ScatterNode proto.InternalMessageInfo

func (m *ScatterNode) GetXInt32() int32 {
	if m != nil {
		return m.XInt32
	}
	return 0
}

func (m *ScatterNode) GetXInt64() int64 {
	if m != nil {
		return m.XInt64
	}
	return 0
}

func (m *ScatterNode) GetYInt32() int32 {
	if m != nil {
		return m.YInt32
	}
	return 0
}

func (m *ScatterNode) GetYInt64() int64 {
	if m != nil {
		return m.YInt64
	}
	return 0
}

// ScatterData - scatter data
//             - 散点图数据
type ScatterData struct {
	XType                ValueType      `protobuf:"varint,1,opt,name=xType,proto3,enum=viewerdbpb.ValueType" json:"xType,omitempty"`
	YType                ValueType      `protobuf:"varint,2,opt,name=yType,proto3,enum=viewerdbpb.ValueType" json:"yType,omitempty"`
	Data                 []*ScatterNode `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ScatterData) Reset()         { *m = ScatterData{} }
func (m *ScatterData) String() string { return proto.CompactTextString(m) }
func (*ScatterData) ProtoMessage()    {}
func (*ScatterData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{10}
}
func (m *ScatterData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScatterData.Unmarshal(m, b)
}
func (m *ScatterData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScatterData.Marshal(b, m, deterministic)
}
func (dst *ScatterData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScatterData.Merge(dst, src)
}
func (m *ScatterData) XXX_Size() int {
	return xxx_messageInfo_ScatterData.Size(m)
}
func (m *ScatterData) XXX_DiscardUnknown() {
	xxx_messageInfo_ScatterData.DiscardUnknown(m)
}

var xxx_messageInfo_ScatterData proto.InternalMessageInfo

func (m *ScatterData) GetXType() ValueType {
	if m != nil {
		return m.XType
	}
	return ValueType_STRING
}

func (m *ScatterData) GetYType() ValueType {
	if m != nil {
		return m.YType
	}
	return ValueType_STRING
}

func (m *ScatterData) GetData() []*ScatterNode {
	if m != nil {
		return m.Data
	}
	return nil
}

// BoxplotNode - boxplot node
//             - 散点图数据
type BoxplotNode struct {
	Name                 string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ValType              ValueType `protobuf:"varint,2,opt,name=valType,proto3,enum=viewerdbpb.ValueType" json:"valType,omitempty"`
	ArrInt32             []int32   `protobuf:"varint,3,rep,packed,name=arrInt32,proto3" json:"arrInt32,omitempty"`
	ArrInt64             []int64   `protobuf:"varint,4,rep,packed,name=arrInt64,proto3" json:"arrInt64,omitempty"`
	ArrFloat32           []float32 `protobuf:"fixed32,5,rep,packed,name=arrFloat32,proto3" json:"arrFloat32,omitempty"`
	ArrFloat64           []float64 `protobuf:"fixed64,6,rep,packed,name=arrFloat64,proto3" json:"arrFloat64,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BoxplotNode) Reset()         { *m = BoxplotNode{} }
func (m *BoxplotNode) String() string { return proto.CompactTextString(m) }
func (*BoxplotNode) ProtoMessage()    {}
func (*BoxplotNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{11}
}
func (m *BoxplotNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxplotNode.Unmarshal(m, b)
}
func (m *BoxplotNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxplotNode.Marshal(b, m, deterministic)
}
func (dst *BoxplotNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxplotNode.Merge(dst, src)
}
func (m *BoxplotNode) XXX_Size() int {
	return xxx_messageInfo_BoxplotNode.Size(m)
}
func (m *BoxplotNode) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxplotNode.DiscardUnknown(m)
}

var xxx_messageInfo_BoxplotNode proto.InternalMessageInfo

func (m *BoxplotNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BoxplotNode) GetValType() ValueType {
	if m != nil {
		return m.ValType
	}
	return ValueType_STRING
}

func (m *BoxplotNode) GetArrInt32() []int32 {
	if m != nil {
		return m.ArrInt32
	}
	return nil
}

func (m *BoxplotNode) GetArrInt64() []int64 {
	if m != nil {
		return m.ArrInt64
	}
	return nil
}

func (m *BoxplotNode) GetArrFloat32() []float32 {
	if m != nil {
		return m.ArrFloat32
	}
	return nil
}

func (m *BoxplotNode) GetArrFloat64() []float64 {
	if m != nil {
		return m.ArrFloat64
	}
	return nil
}

// BoxplotData - boxplot data
//             - 散点图数据
type BoxplotData struct {
	Data                 []*BoxplotNode `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BoxplotData) Reset()         { *m = BoxplotData{} }
func (m *BoxplotData) String() string { return proto.CompactTextString(m) }
func (*BoxplotData) ProtoMessage()    {}
func (*BoxplotData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{12}
}
func (m *BoxplotData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxplotData.Unmarshal(m, b)
}
func (m *BoxplotData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxplotData.Marshal(b, m, deterministic)
}
func (dst *BoxplotData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxplotData.Merge(dst, src)
}
func (m *BoxplotData) XXX_Size() int {
	return xxx_messageInfo_BoxplotData.Size(m)
}
func (m *BoxplotData) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxplotData.DiscardUnknown(m)
}

var xxx_messageInfo_BoxplotData proto.InternalMessageInfo

func (m *BoxplotData) GetData() []*BoxplotNode {
	if m != nil {
		return m.Data
	}
	return nil
}

// ViewerData - viewer data
//            - viewer数据
type ViewerData struct {
	// type
	Type ViewerType `protobuf:"varint,1,opt,name=type,proto3,enum=viewerdbpb.ViewerType" json:"type,omitempty"`
	// title
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// token
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*ViewerData_Graph
	//	*ViewerData_Json
	//	*ViewerData_Line
	//	*ViewerData_Multi
	//	*ViewerData_Pie
	//	*ViewerData_Scatter
	//	*ViewerData_Boxplot
	Data                 isViewerData_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ViewerData) Reset()         { *m = ViewerData{} }
func (m *ViewerData) String() string { return proto.CompactTextString(m) }
func (*ViewerData) ProtoMessage()    {}
func (*ViewerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_d13ae8603be23b2d, []int{13}
}
func (m *ViewerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewerData.Unmarshal(m, b)
}
func (m *ViewerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewerData.Marshal(b, m, deterministic)
}
func (dst *ViewerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewerData.Merge(dst, src)
}
func (m *ViewerData) XXX_Size() int {
	return xxx_messageInfo_ViewerData.Size(m)
}
func (m *ViewerData) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewerData.DiscardUnknown(m)
}

var xxx_messageInfo_ViewerData proto.InternalMessageInfo

type isViewerData_Data interface {
	isViewerData_Data()
}

type ViewerData_Graph struct {
	Graph *GraphData `protobuf:"bytes,1000,opt,name=graph,proto3,oneof"`
}
type ViewerData_Json struct {
	Json *JSONData `protobuf:"bytes,1001,opt,name=json,proto3,oneof"`
}
type ViewerData_Line struct {
	Line *LineData `protobuf:"bytes,1002,opt,name=line,proto3,oneof"`
}
type ViewerData_Multi struct {
	Multi *MultiData `protobuf:"bytes,1003,opt,name=multi,proto3,oneof"`
}
type ViewerData_Pie struct {
	Pie *PieData `protobuf:"bytes,1004,opt,name=pie,proto3,oneof"`
}
type ViewerData_Scatter struct {
	Scatter *ScatterData `protobuf:"bytes,1005,opt,name=scatter,proto3,oneof"`
}
type ViewerData_Boxplot struct {
	Boxplot *BoxplotData `protobuf:"bytes,1006,opt,name=boxplot,proto3,oneof"`
}

func (*ViewerData_Graph) isViewerData_Data()   {}
func (*ViewerData_Json) isViewerData_Data()    {}
func (*ViewerData_Line) isViewerData_Data()    {}
func (*ViewerData_Multi) isViewerData_Data()   {}
func (*ViewerData_Pie) isViewerData_Data()     {}
func (*ViewerData_Scatter) isViewerData_Data() {}
func (*ViewerData_Boxplot) isViewerData_Data() {}

func (m *ViewerData) GetData() isViewerData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ViewerData) GetType() ViewerType {
	if m != nil {
		return m.Type
	}
	return ViewerType_EMPTY
}

func (m *ViewerData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ViewerData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ViewerData) GetGraph() *GraphData {
	if x, ok := m.GetData().(*ViewerData_Graph); ok {
		return x.Graph
	}
	return nil
}

func (m *ViewerData) GetJson() *JSONData {
	if x, ok := m.GetData().(*ViewerData_Json); ok {
		return x.Json
	}
	return nil
}

func (m *ViewerData) GetLine() *LineData {
	if x, ok := m.GetData().(*ViewerData_Line); ok {
		return x.Line
	}
	return nil
}

func (m *ViewerData) GetMulti() *MultiData {
	if x, ok := m.GetData().(*ViewerData_Multi); ok {
		return x.Multi
	}
	return nil
}

func (m *ViewerData) GetPie() *PieData {
	if x, ok := m.GetData().(*ViewerData_Pie); ok {
		return x.Pie
	}
	return nil
}

func (m *ViewerData) GetScatter() *ScatterData {
	if x, ok := m.GetData().(*ViewerData_Scatter); ok {
		return x.Scatter
	}
	return nil
}

func (m *ViewerData) GetBoxplot() *BoxplotData {
	if x, ok := m.GetData().(*ViewerData_Boxplot); ok {
		return x.Boxplot
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ViewerData) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ViewerData_OneofMarshaler, _ViewerData_OneofUnmarshaler, _ViewerData_OneofSizer, []interface{}{
		(*ViewerData_Graph)(nil),
		(*ViewerData_Json)(nil),
		(*ViewerData_Line)(nil),
		(*ViewerData_Multi)(nil),
		(*ViewerData_Pie)(nil),
		(*ViewerData_Scatter)(nil),
		(*ViewerData_Boxplot)(nil),
	}
}

func _ViewerData_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ViewerData)
	// data
	switch x := m.Data.(type) {
	case *ViewerData_Graph:
		b.EncodeVarint(1000<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Graph); err != nil {
			return err
		}
	case *ViewerData_Json:
		b.EncodeVarint(1001<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Json); err != nil {
			return err
		}
	case *ViewerData_Line:
		b.EncodeVarint(1002<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Line); err != nil {
			return err
		}
	case *ViewerData_Multi:
		b.EncodeVarint(1003<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Multi); err != nil {
			return err
		}
	case *ViewerData_Pie:
		b.EncodeVarint(1004<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Pie); err != nil {
			return err
		}
	case *ViewerData_Scatter:
		b.EncodeVarint(1005<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Scatter); err != nil {
			return err
		}
	case *ViewerData_Boxplot:
		b.EncodeVarint(1006<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Boxplot); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ViewerData.Data has unexpected type %T", x)
	}
	return nil
}

func _ViewerData_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ViewerData)
	switch tag {
	case 1000: // data.graph
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GraphData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Graph{msg}
		return true, err
	case 1001: // data.json
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JSONData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Json{msg}
		return true, err
	case 1002: // data.line
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LineData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Line{msg}
		return true, err
	case 1003: // data.multi
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MultiData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Multi{msg}
		return true, err
	case 1004: // data.pie
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PieData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Pie{msg}
		return true, err
	case 1005: // data.scatter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ScatterData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Scatter{msg}
		return true, err
	case 1006: // data.boxplot
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoxplotData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Boxplot{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ViewerData_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ViewerData)
	// data
	switch x := m.Data.(type) {
	case *ViewerData_Graph:
		s := proto.Size(x.Graph)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Json:
		s := proto.Size(x.Json)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Line:
		s := proto.Size(x.Line)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Multi:
		s := proto.Size(x.Multi)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Pie:
		s := proto.Size(x.Pie)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Scatter:
		s := proto.Size(x.Scatter)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Boxplot:
		s := proto.Size(x.Boxplot)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*GraphNode)(nil), "viewerdbpb.GraphNode")
	proto.RegisterType((*GraphLink)(nil), "viewerdbpb.GraphLink")
	proto.RegisterType((*GraphData)(nil), "viewerdbpb.GraphData")
	proto.RegisterType((*JSONData)(nil), "viewerdbpb.JSONData")
	proto.RegisterType((*LineSeriesData)(nil), "viewerdbpb.LineSeriesData")
	proto.RegisterType((*LineData)(nil), "viewerdbpb.LineData")
	proto.RegisterType((*MultiData)(nil), "viewerdbpb.MultiData")
	proto.RegisterType((*PieDataInfo)(nil), "viewerdbpb.PieDataInfo")
	proto.RegisterType((*PieData)(nil), "viewerdbpb.PieData")
	proto.RegisterType((*ScatterNode)(nil), "viewerdbpb.ScatterNode")
	proto.RegisterType((*ScatterData)(nil), "viewerdbpb.ScatterData")
	proto.RegisterType((*BoxplotNode)(nil), "viewerdbpb.BoxplotNode")
	proto.RegisterType((*BoxplotData)(nil), "viewerdbpb.BoxplotData")
	proto.RegisterType((*ViewerData)(nil), "viewerdbpb.ViewerData")
	proto.RegisterEnum("viewerdbpb.ViewerType", ViewerType_name, ViewerType_value)
	proto.RegisterEnum("viewerdbpb.ValueType", ValueType_name, ValueType_value)
}

func init() { proto.RegisterFile("viewer.proto", fileDescriptor_viewer_d13ae8603be23b2d) }

var fileDescriptor_viewer_d13ae8603be23b2d = []byte{
	// 875 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x95, 0x5d, 0x6e, 0xe3, 0x36,
	0x10, 0xc7, 0x23, 0x4b, 0xb2, 0xa3, 0x71, 0x11, 0x08, 0xec, 0x36, 0x25, 0x16, 0x41, 0x21, 0xa8,
	0x2f, 0x46, 0x16, 0x48, 0x81, 0xc4, 0xf0, 0x43, 0xdf, 0x92, 0xd6, 0x9b, 0x78, 0xe1, 0x38, 0x06,
	0xed, 0x2e, 0xba, 0x4f, 0x85, 0x12, 0xb1, 0xa9, 0x1a, 0x45, 0x32, 0x24, 0x6d, 0x6a, 0xef, 0x39,
	0x7a, 0x9c, 0x9e, 0xa0, 0x67, 0xe8, 0x01, 0xfa, 0x7d, 0x86, 0x62, 0x86, 0x94, 0x4c, 0x63, 0xd5,
	0xf6, 0x6d, 0x66, 0xf8, 0xa3, 0x66, 0xe6, 0xcf, 0x21, 0x05, 0x1f, 0x3c, 0x25, 0xf2, 0x07, 0x59,
	0x9c, 0xac, 0x8a, 0xbc, 0xca, 0x19, 0x28, 0x2f, 0xbe, 0x5d, 0xdd, 0x86, 0xdf, 0x80, 0x77, 0x59,
	0x44, 0xab, 0xef, 0x66, 0x79, 0x2c, 0xd9, 0x01, 0x74, 0x92, 0x98, 0x5b, 0x81, 0x35, 0x70, 0x45,
	0x27, 0x89, 0x19, 0x03, 0x27, 0x8b, 0x1e, 0x25, 0xef, 0x04, 0xd6, 0xc0, 0x13, 0x64, 0x63, 0xac,
	0x4c, 0xde, 0x49, 0x6e, 0x13, 0x45, 0x36, 0x7b, 0x0e, 0xfb, 0x77, 0x51, 0x25, 0xef, 0xf3, 0x62,
	0xc3, 0x1d, 0x62, 0x1b, 0x3f, 0x1c, 0xeb, 0x04, 0xd3, 0x24, 0x7b, 0x60, 0x3e, 0xd8, 0x65, 0x71,
	0xa7, 0x33, 0xa0, 0x89, 0x9f, 0x8b, 0x65, 0x59, 0x51, 0x0a, 0x57, 0x90, 0xdd, 0x96, 0x22, 0x94,
	0xfa, 0x33, 0x5f, 0x46, 0x55, 0xc4, 0x5e, 0x80, 0x9b, 0xe5, 0xb1, 0x2c, 0xb9, 0x15, 0xd8, 0x83,
	0xfe, 0xe9, 0x47, 0x27, 0xdb, 0x86, 0x4e, 0x9a, 0x6e, 0x84, 0x62, 0x10, 0x4e, 0x93, 0xec, 0xa1,
	0xe4, 0x9d, 0x7f, 0x81, 0xb1, 0x32, 0xa1, 0x98, 0xf0, 0x08, 0xf6, 0x5f, 0x2d, 0x6e, 0x66, 0x94,
	0x05, 0x8b, 0xad, 0x0a, 0x2a, 0xd6, 0x13, 0x68, 0x86, 0xef, 0xe0, 0x60, 0x9a, 0x64, 0x72, 0x21,
	0x8b, 0x44, 0x96, 0xc4, 0xd4, 0x0a, 0x59, 0x86, 0x42, 0x47, 0xe0, 0x3d, 0x45, 0xe9, 0xa2, 0x2a,
	0x92, 0xec, 0x9e, 0x92, 0x7a, 0x62, 0x1b, 0x40, 0xad, 0x9e, 0xa2, 0x74, 0x92, 0x55, 0x67, 0xa7,
	0xdc, 0x0e, 0xec, 0x81, 0x2b, 0x1a, 0x7f, 0xbb, 0x36, 0x1a, 0x72, 0x27, 0xb0, 0x07, 0xb6, 0x68,
	0xfc, 0xf0, 0x17, 0x0b, 0xf6, 0x31, 0x39, 0xa5, 0x3d, 0x02, 0x6f, 0x7d, 0xbe, 0x4e, 0xca, 0xe5,
	0x66, 0x55, 0xe7, 0xde, 0x06, 0x58, 0x00, 0x7d, 0x72, 0x76, 0x4a, 0x30, 0x43, 0xec, 0x13, 0x00,
	0x72, 0xcd, 0x32, 0x8c, 0x88, 0xb9, 0xde, 0x94, 0x62, 0x44, 0x30, 0xff, 0xa6, 0xc9, 0x1f, 0xab,
	0xfc, 0x4d, 0x80, 0x9d, 0x42, 0xb7, 0x24, 0x89, 0xb8, 0x24, 0xc9, 0x9f, 0x9b, 0x92, 0xef, 0x0a,
	0x28, 0x34, 0x19, 0x7e, 0x0a, 0xde, 0xf5, 0xdb, 0xb4, 0x4a, 0xa8, 0xbd, 0x43, 0xe8, 0x56, 0xf9,
	0x83, 0xcc, 0xd4, 0x01, 0x7b, 0x42, 0x7b, 0xe1, 0x1b, 0xe8, 0xcf, 0x13, 0x52, 0x60, 0x92, 0x7d,
	0x9b, 0xb7, 0x8a, 0x6f, 0xca, 0xab, 0x66, 0xaa, 0x5d, 0x5e, 0x9c, 0x2d, 0x53, 0xde, 0x57, 0xd0,
	0xd3, 0x9f, 0x6e, 0xfd, 0xec, 0x0b, 0x70, 0xe2, 0xa8, 0x8a, 0xf4, 0x0c, 0x7d, 0x6c, 0x36, 0x64,
	0x54, 0x24, 0x08, 0x0a, 0x1f, 0xa1, 0xbf, 0xb8, 0x8b, 0xaa, 0x4a, 0x16, 0x74, 0xab, 0x0e, 0xa1,
	0xbb, 0x56, 0x05, 0xa9, 0xb9, 0xd7, 0x5e, 0x1d, 0x1f, 0x0d, 0xa9, 0x50, 0x5b, 0x68, 0x0f, 0xe3,
	0x1b, 0xc5, 0xc7, 0x8a, 0xdf, 0x34, 0xfc, 0x46, 0xf1, 0x52, 0xf1, 0xca, 0x0b, 0x7f, 0xb4, 0x9a,
	0x7c, 0xf5, 0xed, 0x58, 0x37, 0x83, 0x71, 0xb0, 0x3b, 0xf0, 0xaf, 0xa3, 0xf4, 0xad, 0xc4, 0x45,
	0xa1, 0x18, 0x84, 0x37, 0x04, 0x77, 0xfe, 0x13, 0xde, 0x68, 0x58, 0xa9, 0x60, 0xbf, 0xaf, 0x82,
	0xd1, 0xb0, 0x56, 0xe1, 0x67, 0x0b, 0xfa, 0x17, 0xf9, 0x7a, 0x95, 0xe6, 0x15, 0xc9, 0xc0, 0xc0,
	0x99, 0x19, 0xb2, 0xa2, 0xcd, 0x3e, 0x83, 0xde, 0x53, 0x94, 0xfe, 0x7f, 0xfe, 0x9a, 0xc2, 0x23,
	0x8c, 0x8a, 0x62, 0xe7, 0xf6, 0xd4, 0xfe, 0x76, 0x6d, 0x7b, 0x7b, 0x6a, 0x1f, 0x07, 0x3a, 0x2a,
	0x8a, 0x97, 0x69, 0x1e, 0xe1, 0x4e, 0x37, 0xb0, 0x07, 0x1d, 0x61, 0x44, 0xcc, 0xf5, 0xd1, 0x90,
	0x77, 0x03, 0x7b, 0x60, 0x09, 0x23, 0x12, 0x7e, 0xde, 0xf4, 0xa2, 0x25, 0x56, 0x42, 0x58, 0xef,
	0x0b, 0x61, 0xb4, 0xac, 0x85, 0xf8, 0xc9, 0x06, 0x78, 0x4d, 0x00, 0xed, 0x3d, 0x06, 0xa7, 0xda,
	0x9e, 0xce, 0xe1, 0x4e, 0xc3, 0x64, 0x52, 0xc7, 0xc4, 0xb0, 0x67, 0xe0, 0x56, 0x49, 0x95, 0xd6,
	0x2f, 0xb0, 0x72, 0x28, 0x8a, 0x17, 0x82, 0x86, 0x18, 0xa3, 0xe8, 0xb0, 0x13, 0x70, 0xef, 0xf1,
	0x39, 0xe3, 0xbf, 0xf6, 0x02, 0xab, 0xf5, 0xa1, 0xc3, 0xf4, 0x57, 0x7b, 0x42, 0x61, 0xd8, 0xc3,
	0xf7, 0x65, 0x9e, 0xf1, 0xdf, 0x14, 0xfe, 0xcc, 0xc4, 0xeb, 0x37, 0xf0, 0x6a, 0x4f, 0x10, 0x84,
	0x70, 0x9a, 0x64, 0x92, 0xff, 0xde, 0x02, 0xd7, 0xaf, 0x12, 0xc2, 0x08, 0x61, 0x25, 0x8f, 0x78,
	0x97, 0xf9, 0x1f, 0x2d, 0x95, 0x34, 0xb7, 0x1c, 0x2b, 0x21, 0x8c, 0x0d, 0xc0, 0x5e, 0x25, 0x92,
	0xff, 0xa9, 0xe8, 0x0f, 0x5b, 0x2e, 0xd7, 0xd5, 0x9e, 0x40, 0x84, 0x0d, 0xa1, 0x57, 0xaa, 0x41,
	0xe3, 0x7f, 0x29, 0xba, 0x6d, 0x08, 0xf5, 0x8e, 0x1a, 0xc5, 0x5d, 0xb7, 0xea, 0x54, 0xf8, 0xdf,
	0x2d, 0xbb, 0x8c, 0x83, 0xc5, 0x5d, 0x1a, 0xbd, 0xe8, 0xaa, 0x33, 0x3e, 0x8e, 0xeb, 0xd3, 0xa3,
	0x01, 0xf4, 0xc0, 0x1d, 0x5f, 0xcf, 0x97, 0x6f, 0xfc, 0x3d, 0x34, 0x2f, 0xc5, 0xf9, 0xfc, 0xca,
	0xb7, 0xd8, 0x3e, 0x38, 0x28, 0x99, 0xdf, 0x41, 0x6b, 0x3a, 0x99, 0x8d, 0x7d, 0x1b, 0x97, 0xaf,
	0xbf, 0x9a, 0x2e, 0x27, 0xbe, 0xc3, 0x7a, 0x60, 0xcf, 0x27, 0x63, 0xdf, 0x65, 0x7d, 0xe8, 0x2d,
	0xbe, 0x38, 0x5f, 0x2e, 0xc7, 0xc2, 0xef, 0xa2, 0x73, 0x71, 0xf3, 0xf5, 0x7c, 0x7a, 0xb3, 0xf4,
	0x7b, 0xc7, 0x97, 0xe0, 0x35, 0xe3, 0xce, 0x00, 0xba, 0x8b, 0xa5, 0x98, 0xcc, 0x2e, 0x55, 0x96,
	0xc9, 0x6c, 0x79, 0x76, 0xea, 0x5b, 0xda, 0x1c, 0x0d, 0xfd, 0x0e, 0xee, 0x7d, 0x39, 0xbd, 0x39,
	0xc7, 0xb8, 0xdd, 0x38, 0xa3, 0xa1, 0xef, 0xdc, 0x76, 0xe9, 0x1f, 0x7f, 0xf6, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xec, 0xcc, 0xf6, 0x51, 0xf3, 0x07, 0x00, 0x00,
}
