// Code generated by protoc-gen-go. DO NOT EDIT.
// source: viewer.proto

package viewerdbpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ViewerType int32

const (
	ViewerType_EMPTY ViewerType = 0
	ViewerType_GRAPH ViewerType = 1
	ViewerType_JSON  ViewerType = 2
)

var ViewerType_name = map[int32]string{
	0: "EMPTY",
	1: "GRAPH",
	2: "JSON",
}
var ViewerType_value = map[string]int32{
	"EMPTY": 0,
	"GRAPH": 1,
	"JSON":  2,
}

func (x ViewerType) String() string {
	return proto.EnumName(ViewerType_name, int32(x))
}
func (ViewerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_viewer_8092c8b6e5f0756f, []int{0}
}

type GraphNode struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphNode) Reset()         { *m = GraphNode{} }
func (m *GraphNode) String() string { return proto.CompactTextString(m) }
func (*GraphNode) ProtoMessage()    {}
func (*GraphNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_8092c8b6e5f0756f, []int{0}
}
func (m *GraphNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphNode.Unmarshal(m, b)
}
func (m *GraphNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphNode.Marshal(b, m, deterministic)
}
func (dst *GraphNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphNode.Merge(dst, src)
}
func (m *GraphNode) XXX_Size() int {
	return xxx_messageInfo_GraphNode.Size(m)
}
func (m *GraphNode) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphNode.DiscardUnknown(m)
}

var xxx_messageInfo_GraphNode proto.InternalMessageInfo

func (m *GraphNode) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GraphNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphNode) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GraphNode) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type GraphLink struct {
	Src                  int32    `protobuf:"varint,1,opt,name=src,proto3" json:"src,omitempty"`
	Dest                 int32    `protobuf:"varint,2,opt,name=dest,proto3" json:"dest,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphLink) Reset()         { *m = GraphLink{} }
func (m *GraphLink) String() string { return proto.CompactTextString(m) }
func (*GraphLink) ProtoMessage()    {}
func (*GraphLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_8092c8b6e5f0756f, []int{1}
}
func (m *GraphLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphLink.Unmarshal(m, b)
}
func (m *GraphLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphLink.Marshal(b, m, deterministic)
}
func (dst *GraphLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphLink.Merge(dst, src)
}
func (m *GraphLink) XXX_Size() int {
	return xxx_messageInfo_GraphLink.Size(m)
}
func (m *GraphLink) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphLink.DiscardUnknown(m)
}

var xxx_messageInfo_GraphLink proto.InternalMessageInfo

func (m *GraphLink) GetSrc() int32 {
	if m != nil {
		return m.Src
	}
	return 0
}

func (m *GraphLink) GetDest() int32 {
	if m != nil {
		return m.Dest
	}
	return 0
}

func (m *GraphLink) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GraphData struct {
	Nodes                []*GraphNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links                []*GraphLink `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GraphData) Reset()         { *m = GraphData{} }
func (m *GraphData) String() string { return proto.CompactTextString(m) }
func (*GraphData) ProtoMessage()    {}
func (*GraphData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_8092c8b6e5f0756f, []int{2}
}
func (m *GraphData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphData.Unmarshal(m, b)
}
func (m *GraphData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphData.Marshal(b, m, deterministic)
}
func (dst *GraphData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphData.Merge(dst, src)
}
func (m *GraphData) XXX_Size() int {
	return xxx_messageInfo_GraphData.Size(m)
}
func (m *GraphData) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphData.DiscardUnknown(m)
}

var xxx_messageInfo_GraphData proto.InternalMessageInfo

func (m *GraphData) GetNodes() []*GraphNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *GraphData) GetLinks() []*GraphLink {
	if m != nil {
		return m.Links
	}
	return nil
}

type JSONData struct {
	Str                  string   `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JSONData) Reset()         { *m = JSONData{} }
func (m *JSONData) String() string { return proto.CompactTextString(m) }
func (*JSONData) ProtoMessage()    {}
func (*JSONData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_8092c8b6e5f0756f, []int{3}
}
func (m *JSONData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSONData.Unmarshal(m, b)
}
func (m *JSONData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSONData.Marshal(b, m, deterministic)
}
func (dst *JSONData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSONData.Merge(dst, src)
}
func (m *JSONData) XXX_Size() int {
	return xxx_messageInfo_JSONData.Size(m)
}
func (m *JSONData) XXX_DiscardUnknown() {
	xxx_messageInfo_JSONData.DiscardUnknown(m)
}

var xxx_messageInfo_JSONData proto.InternalMessageInfo

func (m *JSONData) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

type ViewerData struct {
	Type  ViewerType `protobuf:"varint,1,opt,name=type,proto3,enum=viewerdbpb.ViewerType" json:"type,omitempty"`
	Title string     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Token string     `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*ViewerData_Graph
	//	*ViewerData_Json
	Data                 isViewerData_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ViewerData) Reset()         { *m = ViewerData{} }
func (m *ViewerData) String() string { return proto.CompactTextString(m) }
func (*ViewerData) ProtoMessage()    {}
func (*ViewerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_viewer_8092c8b6e5f0756f, []int{4}
}
func (m *ViewerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewerData.Unmarshal(m, b)
}
func (m *ViewerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewerData.Marshal(b, m, deterministic)
}
func (dst *ViewerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewerData.Merge(dst, src)
}
func (m *ViewerData) XXX_Size() int {
	return xxx_messageInfo_ViewerData.Size(m)
}
func (m *ViewerData) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewerData.DiscardUnknown(m)
}

var xxx_messageInfo_ViewerData proto.InternalMessageInfo

type isViewerData_Data interface {
	isViewerData_Data()
}

type ViewerData_Graph struct {
	Graph *GraphData `protobuf:"bytes,1000,opt,name=graph,proto3,oneof"`
}
type ViewerData_Json struct {
	Json *JSONData `protobuf:"bytes,1001,opt,name=json,proto3,oneof"`
}

func (*ViewerData_Graph) isViewerData_Data() {}
func (*ViewerData_Json) isViewerData_Data()  {}

func (m *ViewerData) GetData() isViewerData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ViewerData) GetType() ViewerType {
	if m != nil {
		return m.Type
	}
	return ViewerType_EMPTY
}

func (m *ViewerData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ViewerData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ViewerData) GetGraph() *GraphData {
	if x, ok := m.GetData().(*ViewerData_Graph); ok {
		return x.Graph
	}
	return nil
}

func (m *ViewerData) GetJson() *JSONData {
	if x, ok := m.GetData().(*ViewerData_Json); ok {
		return x.Json
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ViewerData) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ViewerData_OneofMarshaler, _ViewerData_OneofUnmarshaler, _ViewerData_OneofSizer, []interface{}{
		(*ViewerData_Graph)(nil),
		(*ViewerData_Json)(nil),
	}
}

func _ViewerData_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ViewerData)
	// data
	switch x := m.Data.(type) {
	case *ViewerData_Graph:
		b.EncodeVarint(1000<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Graph); err != nil {
			return err
		}
	case *ViewerData_Json:
		b.EncodeVarint(1001<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Json); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ViewerData.Data has unexpected type %T", x)
	}
	return nil
}

func _ViewerData_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ViewerData)
	switch tag {
	case 1000: // data.graph
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GraphData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Graph{msg}
		return true, err
	case 1001: // data.json
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JSONData)
		err := b.DecodeMessage(msg)
		m.Data = &ViewerData_Json{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ViewerData_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ViewerData)
	// data
	switch x := m.Data.(type) {
	case *ViewerData_Graph:
		s := proto.Size(x.Graph)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ViewerData_Json:
		s := proto.Size(x.Json)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*GraphNode)(nil), "viewerdbpb.GraphNode")
	proto.RegisterType((*GraphLink)(nil), "viewerdbpb.GraphLink")
	proto.RegisterType((*GraphData)(nil), "viewerdbpb.GraphData")
	proto.RegisterType((*JSONData)(nil), "viewerdbpb.JSONData")
	proto.RegisterType((*ViewerData)(nil), "viewerdbpb.ViewerData")
	proto.RegisterEnum("viewerdbpb.ViewerType", ViewerType_name, ViewerType_value)
}

func init() { proto.RegisterFile("viewer.proto", fileDescriptor_viewer_8092c8b6e5f0756f) }

var fileDescriptor_viewer_8092c8b6e5f0756f = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x86, 0x69, 0x69, 0xb9, 0xf4, 0xdc, 0x1b, 0xd2, 0x4c, 0xb8, 0x66, 0x62, 0x5c, 0x34, 0x5d,
	0x11, 0x30, 0x5d, 0xe0, 0x13, 0x68, 0x24, 0x10, 0xa3, 0x48, 0x46, 0x62, 0xe2, 0xca, 0x14, 0x3a,
	0xc1, 0x11, 0xec, 0x34, 0xed, 0x44, 0x83, 0x6f, 0xe8, 0x9b, 0xe8, 0x5b, 0x98, 0x73, 0x06, 0x90,
	0x05, 0xee, 0xfe, 0x73, 0xf2, 0xcd, 0xf9, 0xff, 0xbf, 0x29, 0xfc, 0x7b, 0x55, 0xf2, 0x4d, 0x96,
	0x49, 0x51, 0x6a, 0xa3, 0x19, 0xd8, 0x29, 0x9b, 0x15, 0xb3, 0xf8, 0x11, 0x82, 0x61, 0x99, 0x16,
	0x4f, 0x63, 0x9d, 0x49, 0xd6, 0x02, 0x57, 0x65, 0xdc, 0x89, 0x9c, 0x8e, 0x2f, 0x5c, 0x95, 0x31,
	0x06, 0x5e, 0x9e, 0xbe, 0x48, 0xee, 0x46, 0x4e, 0x27, 0x10, 0xa4, 0x71, 0x57, 0xa9, 0x77, 0xc9,
	0xeb, 0x44, 0x91, 0x66, 0xc7, 0xd0, 0x9c, 0xa7, 0x46, 0x2e, 0x74, 0xb9, 0xe6, 0x1e, 0xb1, 0xbb,
	0x39, 0x1e, 0x6c, 0x0c, 0xae, 0x55, 0xbe, 0x64, 0x21, 0xd4, 0xab, 0x72, 0xbe, 0x71, 0x40, 0x89,
	0xe7, 0x32, 0x59, 0x19, 0xb2, 0xf0, 0x05, 0xe9, 0x43, 0x16, 0xb1, 0xdc, 0x9c, 0xb9, 0x4c, 0x4d,
	0xca, 0x7a, 0xe0, 0xe7, 0x3a, 0x93, 0x15, 0x77, 0xa2, 0x7a, 0xe7, 0x6f, 0xff, 0x7f, 0xf2, 0x53,
	0x28, 0xd9, 0xb5, 0x11, 0x96, 0x41, 0x78, 0xa5, 0xf2, 0x65, 0xc5, 0xdd, 0x5f, 0x60, 0x4c, 0x26,
	0x2c, 0x13, 0x9f, 0x40, 0xf3, 0xea, 0xee, 0x76, 0x4c, 0x2e, 0x18, 0xd6, 0x94, 0x14, 0x36, 0x10,
	0x28, 0xe3, 0x0f, 0x07, 0xe0, 0x9e, 0x5e, 0x13, 0xd0, 0x05, 0xcf, 0xac, 0x0b, 0x49, 0x44, 0xab,
	0x7f, 0xb4, 0x7f, 0xd8, 0x52, 0xd3, 0x75, 0x21, 0x05, 0x31, 0xac, 0x0d, 0xbe, 0x51, 0x66, 0xb5,
	0xfd, 0x96, 0x76, 0xa0, 0xad, 0x5e, 0xca, 0x9c, 0xaa, 0xe2, 0x16, 0x07, 0x96, 0x80, 0xbf, 0xc0,
	0x60, 0xfc, 0xf3, 0x4f, 0xe4, 0x1c, 0x8c, 0x8c, 0xf6, 0xa3, 0x9a, 0xb0, 0x18, 0xeb, 0x81, 0xf7,
	0x5c, 0xe9, 0x9c, 0x7f, 0x59, 0xbc, 0xbd, 0x8f, 0x6f, 0xdb, 0x8c, 0x6a, 0x82, 0xa0, 0x8b, 0x06,
	0x78, 0x59, 0x6a, 0xd2, 0xee, 0xe9, 0xb6, 0x0a, 0x86, 0x64, 0x01, 0xf8, 0x83, 0x9b, 0xc9, 0xf4,
	0x21, 0xac, 0xa1, 0x1c, 0x8a, 0xf3, 0xc9, 0x28, 0x74, 0x58, 0x13, 0x3c, 0x7c, 0x1f, 0xba, 0xb3,
	0x06, 0xfd, 0x39, 0x67, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x00, 0xb1, 0x5f, 0x49, 0x02,
	0x00, 0x00,
}
